#! /bin/bash
### BEGIN INIT INFO
# Provides:          uwsgi_project
# Required-Start:    $local_fs $remote_fs $networking
# Required-Stop:     $local_fs $remote_fs $networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts uwsgi_project
# Description:       Starts and stops uwsgi_project as needed
### END INIT INFO
# /etc/init.d/uwsgi_project
#

daemon=/usr/local/bin/uwsgi
pid=/var/run/uwsgi.pid
args="--ini /srv/graphsense-dashboard/dashboard.ini"
me=`basename $0`

# Carry out specific functions when asked to by the system
case "$1" in
    start)
        echo "Starting $me"
        start-stop-daemon -p $pid --start --exec $daemon -- $args
        ;;
    stop)
        echo "Stopping script $me"
        start-stop-daemon --signal QUIT -p $pid --stop $daemon -- $args
        ;;
    reload | restart)
        echo "Restarting worker threads"
        kill -HUP $(cat $pid)
        ;;
    *)
        echo "Usage: /etc/init.d/$me {start|stop|reload}"
        exit 1
    ;;
esac

exit 0
