module Api.DecoderContractTest exposing (suite)

{-| The generated `Api.Data` decoders are a snapshot of the OpenAPI spec taken
whenever someone last ran `make openapi`. The backend keeps moving. When the
two drift apart nothing fails loudly — a renamed or newly-required field just
makes a decoder reject the whole response, and the UI shows an empty panel.

These tests feed every decoder the response example the spec itself documents
(see `tests/Fixtures/Api.elm`, generated by `tools/gen_api_fixtures.mjs`). A
failure here means "the client no longer understands what the API says it
returns" — regenerate the client, or pin the fixture corpus deliberately.

-}

import Api.Data
import Dict
import Expect
import Fixtures.Api as Fixture
import Json.Decode exposing (Decoder)
import Test exposing (Test, describe, test)


{-| Decoding must succeed _and_ the error must be readable when it does not.
-}
decodes : String -> Decoder a -> String -> Test
decodes name decoder json =
    test name <|
        \_ ->
            case Json.Decode.decodeString decoder json of
                Ok _ ->
                    Expect.pass

                Err error ->
                    Expect.fail
                        ("the spec example for "
                            ++ name
                            ++ " no longer decodes (spec "
                            ++ Fixture.specVersion
                            ++ "):\n"
                            ++ Json.Decode.errorToString error
                        )


suite : Test
suite =
    describe "Api.Data decoders accept the documented responses"
        [ describe "every spec example decodes"
            [ decodes "address" Api.Data.addressDecoder Fixture.address
            , decodes "address_tag" Api.Data.addressTagDecoder Fixture.addressTag
            , decodes "address_tags" Api.Data.addressTagsDecoder Fixture.addressTags
            , decodes "address_tx_utxo" Api.Data.addressTxUtxoDecoder Fixture.addressTxUtxo
            , decodes "address_txs" Api.Data.addressTxsDecoder Fixture.addressTxs
            , decodes "block" Api.Data.blockDecoder Fixture.block
            , decodes "block_at_date" Api.Data.blockAtDateDecoder Fixture.blockAtDate
            , decodes "cluster" Api.Data.clusterDecoder Fixture.cluster
            , decodes "currency_stats" Api.Data.currencyStatsDecoder Fixture.currencyStats
            , decodes "entity" Api.Data.clusterDecoder Fixture.entity
            , decodes "link_utxo" Api.Data.linkUtxoDecoder Fixture.linkUtxo
            , decodes "links" Api.Data.linksDecoder Fixture.links
            , decodes "neighbor_address" Api.Data.neighborAddressDecoder Fixture.neighborAddress
            , decodes "neighbor_cluster" Api.Data.neighborClusterDecoder Fixture.neighborCluster
            , decodes "rate" Api.Data.rateDecoder Fixture.rate
            , decodes "rates" Api.Data.ratesDecoder Fixture.rates
            , decodes "search_result" Api.Data.searchResultDecoder Fixture.searchResult
            , decodes "search_result_by_currency" Api.Data.searchResultByCurrencyDecoder Fixture.searchResultByCurrency
            , decodes "stats" Api.Data.statsDecoder Fixture.stats
            , decodes "tag_summary" Api.Data.tagSummaryDecoder Fixture.tagSummary
            , decodes "token_config" Api.Data.tokenConfigDecoder Fixture.tokenConfig
            , decodes "token_configs" Api.Data.tokenConfigsDecoder Fixture.tokenConfigs
            , decodes "tx_account" Api.Data.txAccountDecoder Fixture.txAccount
            , decodes "tx_ref" Api.Data.txRefDecoder Fixture.txRef
            , decodes "tx_summary" Api.Data.txSummaryDecoder Fixture.txSummary
            , decodes "tx_utxo" Api.Data.txUtxoDecoder Fixture.txUtxo
            , decodes "tx_value" Api.Data.txValueDecoder Fixture.txValue
            , decodes "values" Api.Data.valuesDecoder Fixture.values
            ]
        , describe "an address with no transactions of its own"
            -- first_tx/last_tx are nullable and NOT required in the spec: an
            -- address that only ever paid a failed-tx gas fee, only received a
            -- coinbase reward, or whose whole history is in tokens the backend
            -- does not index has neither. The generated client had both as
            -- required, so such a body failed to decode entirely and the UI
            -- showed "Unexpected data format ... Expecting an OBJECT with a
            -- field named `last_tx`" instead of the address.
            [ test "decodes with the fields omitted, as exclude_none serializes them" <|
                \_ ->
                    txlessAddress
                        |> Json.Decode.decodeString Api.Data.addressDecoder
                        |> Result.map (\a -> ( a.firstTx, a.lastTx ))
                        |> Expect.equal (Ok ( Nothing, Nothing ))
            , test "decodes with the fields explicitly null" <|
                \_ ->
                    txlessAddressWithNulls
                        |> Json.Decode.decodeString Api.Data.addressDecoder
                        |> Result.map (\a -> ( a.firstTx, a.lastTx ))
                        |> Expect.equal (Ok ( Nothing, Nothing ))
            , test "a cluster still requires them — only local synthesis may omit them" <|
                \_ ->
                    -- the Maybe on Api.Data.Cluster exists for Util.Data.selfCluster,
                    -- NOT because a server may leave them out
                    """{"currency":"eth","entity":1,"cluster":1,"root_address":"0xab","balance":{"value":0,"fiat_values":[]},"total_received":{"value":0,"fiat_values":[]},"total_spent":{"value":0,"fiat_values":[]},"in_degree":0,"out_degree":0,"no_addresses":1,"no_incoming_txs":0,"no_outgoing_txs":0,"no_address_tags":0}"""
                        |> Json.Decode.decodeString Api.Data.clusterDecoder
                        |> Result.toMaybe
                        |> Expect.equal Nothing
            ]
        , describe "a dex swap leg's curated display metadata and fiat"
            -- A swap leg may move a token the dashboard's own token list does
            -- not carry. The adapter only serves a dex_swap when both legs are
            -- on its curated list, so it can name the token for us: the
            -- optional per-leg symbol/decimals are trusted display metadata,
            -- and per-leg fiat arrives only when the backend could price that
            -- leg. All six are absent from the spec and from any baseline
            -- body, so these pin the hand patch in openapi/src/Api/Data.elm.
            [ test "decodes symbol, decimals and fiat when the adapter sends them" <|
                \_ ->
                    enrichedDexSwap
                        |> Json.Decode.decodeString Api.Data.externalConversionDecoder
                        |> Result.map
                            (\c ->
                                -- Elm has no four-tuple
                                { toAssetSymbol = c.toAssetSymbol
                                , toAssetDecimals = c.toAssetDecimals
                                , fromAmountFiatValues = c.fromAmountFiatValues
                                , toAmountFiatValues = c.toAmountFiatValues
                                }
                            )
                        |> Expect.equal
                            (Ok
                                { toAssetSymbol = Just "KAISER"
                                , toAssetDecimals = Just 9
                                , fromAmountFiatValues = Just [ { code = "usd", value = 60.0 } ]
                                , toAmountFiatValues = Nothing
                                }
                            )
            , test "a baseline body without them still decodes" <|
                \_ ->
                    baselineDexSwap
                        |> Json.Decode.decodeString Api.Data.externalConversionDecoder
                        |> Result.map
                            (\c ->
                                [ c.fromAssetSymbol /= Nothing
                                , c.toAssetSymbol /= Nothing
                                , c.fromAssetDecimals /= Nothing
                                , c.toAssetDecimals /= Nothing
                                , c.fromAmountFiatValues /= Nothing
                                , c.toAmountFiatValues /= Nothing
                                ]
                            )
                        |> Expect.equal (Ok [ False, False, False, False, False, False ])
            , test "decodes the from leg's symbol and decimals when it is a token" <|
                -- the from-leg registration (Update.Pathfinder) fires only on
                -- a decoded symbol and decimals: a typo in either key would
                -- silently turn them into Nothing
                \_ ->
                    tokenInputDexSwap
                        |> Json.Decode.decodeString Api.Data.externalConversionDecoder
                        |> Result.map legMetadata
                        |> Expect.equal
                            (Ok
                                { fromAssetSymbol = Just "USDT"
                                , fromAssetDecimals = Just 6
                                , toAssetSymbol = Nothing
                                , toAssetDecimals = Nothing
                                }
                            )
            , test "a null from-leg symbol decodes to Nothing" <|
                \_ ->
                    tokenInputDexSwap
                        |> String.replace "\"from_asset_symbol\":\"USDT\"" "\"from_asset_symbol\":null"
                        |> Json.Decode.decodeString Api.Data.externalConversionDecoder
                        |> Result.map legMetadata
                        |> Expect.equal
                            (Ok
                                { fromAssetSymbol = Nothing
                                , fromAssetDecimals = Just 6
                                , toAssetSymbol = Nothing
                                , toAssetDecimals = Nothing
                                }
                            )
            ]
        , describe "the client is stricter than the spec about nulls"
            -- The spec types both of these `anyOf: [string, null]`, the client
            -- as a plain String. A live instance does send them (checked
            -- 2026-07-28), which is why they are in the list above — but an
            -- explicit null would still take down the whole response. These
            -- pin that gap: if the client is ever regenerated faithfully the
            -- fields become Maybe, and these two tests go red to say so.
            [ test "a null tag_type is rejected" <|
                \_ ->
                    """{"address":"a","currency":"btc","is_cluster_definer":false,"label":"l","tag_type":null,"tagpack_creator":"c","tagpack_is_public":true,"tagpack_title":"t"}"""
                        |> Json.Decode.decodeString Api.Data.addressTagDecoder
                        |> Result.toMaybe
                        |> Expect.equal Nothing
            , test "a null request_timestamp is rejected" <|
                \_ ->
                    """{"currencies":[],"version":"1.0.0","request_timestamp":null}"""
                        |> Json.Decode.decodeString Api.Data.statsDecoder
                        |> Result.toMaybe
                        |> Expect.equal Nothing
            ]
        , describe "the fields the UI reads actually arrive"
            -- Decoding to a record full of Nothings would still pass above, so
            -- spot-check the values the Pathfinder views and tables depend on.
            [ test "an address carries balance, cluster id and tx counts" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.addressDecoder Fixture.address
                        |> Result.map
                            (\a ->
                                { address = a.address
                                , currency = a.currency
                                , cluster = a.cluster
                                , balance = a.balance.value
                                , noIncomingTxs = a.noIncomingTxs
                                , noOutgoingTxs = a.noOutgoingTxs
                                , fiatCodes = a.balance.fiatValues |> List.map .code
                                }
                            )
                        |> Expect.equal
                            (Ok
                                { address = "1Archive1n2C579dMsAu3iC6tWzuQJz8dN"
                                , currency = "btc"
                                , cluster = 264711
                                , balance = 1000000
                                , noIncomingTxs = 200
                                , noOutgoingTxs = 100
                                , fiatCodes = [ "eur", "usd" ]
                                }
                            )
            , test "a utxo transaction carries its inputs and outputs" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.txUtxoDecoder Fixture.txUtxo
                        |> Result.map
                            (\tx ->
                                ( tx.txHash
                                , tx.inputs |> Maybe.map List.length
                                , tx.outputs |> Maybe.map List.length
                                )
                            )
                        |> Result.map (\( hash, i, o ) -> ( hash /= "", i /= Just 0, o /= Just 0 ))
                        |> Expect.equal (Ok ( True, True, True ))
            , test "an account transaction carries its value and endpoints" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.txAccountDecoder Fixture.txAccount
                        |> Result.map (\tx -> ( tx.fromAddress /= "", tx.toAddress /= "", tx.value.value ))
                        |> Result.map (\( f, t, v ) -> ( f, t, v > 0 ))
                        |> Expect.equal (Ok ( True, True, True ))
            , test "a neighbor carries the address it points at and the value moved" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.neighborAddressDecoder Fixture.neighborAddress
                        |> Result.map (\n -> ( n.address.address /= "", n.noTxs > 0 ))
                        |> Expect.equal (Ok ( True, True ))
            , test "a tag summary carries the labels and counts the tag panel shows" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.tagSummaryDecoder Fixture.tagSummary
                        |> Result.map
                            (\t ->
                                ( t.tagCount > 0
                                , t.broadCategory /= ""
                                , Dict.isEmpty t.labelSummary
                                )
                            )
                        |> Expect.equal (Ok ( True, True, False ))
            , test "token configs carry ticker and decimals, which drive every token amount" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.tokenConfigsDecoder Fixture.tokenConfigs
                        |> Result.map
                            (.tokenConfigs
                                >> List.map (\c -> ( c.ticker /= "", c.decimals > 0 ))
                            )
                        |> Result.map (List.all (\( a, b ) -> a && b))
                        |> Expect.equal (Ok True)
            ]
        ]


{-| The all-zero body a backend serves for an address it can see on chain but
has no indexed transactions for. Serialized with exclude\_none, so the two
nullable tx summaries are absent rather than null.
-}
txlessAddress : String
txlessAddress =
    """{"currency":"eth","address":"0xab","entity":1,"cluster":1,"status":"clean","balance":{"value":0,"fiat_values":[]},"total_received":{"value":0,"fiat_values":[]},"total_spent":{"value":0,"fiat_values":[]},"in_degree":0,"out_degree":0,"no_incoming_txs":0,"no_outgoing_txs":0}"""


{-| A dex\_swap as the live baseline serves it, byte for byte: the single row
of harness fixture be8b3e387e9f, recorded 2026-09-22 (the adapter's
`harness/baseline_snapshots/eth/be8b3e387e9f.json`, which is gitignored there).

Exactly the thirteen keys the spec declares, hex amounts, native in and a token
out the baseline does not count as a supported asset.

-}
baselineDexSwap : String
baselineDexSwap =
    """{"conversion_type":"dex_swap","from_address":"0x4c2d696441a11760429cd9845bd84987b9313242","to_address":"0x4c2d696441a11760429cd9845bd84987b9313242","from_asset":"native","to_asset":"0x87b723960c170561e6b7cb74188b5f159e272c74","from_amount":"0x470de4df820000","to_amount":"0x22db8e23bcaee","from_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_I603","to_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_T250","from_network":"eth","to_network":"eth","from_is_supported_asset":true,"to_is_supported_asset":false}"""


{-| The same row as the adapter serves it once it adds curated display
metadata: the thirteen keys plus the token leg's symbol and decimals from its
curated list, and fiat for the leg it could price — the native one here, since
the baseline-parity pin KAISER has no quote.

The three optional keys are added by hand: the snapshot above predates the
enrichment. Symbol and decimals are the curated list's own
(`instance/swap_assets.yaml`); the fiat figure is illustrative.

-}
enrichedDexSwap : String
enrichedDexSwap =
    """{"conversion_type":"dex_swap","from_address":"0x4c2d696441a11760429cd9845bd84987b9313242","to_address":"0x4c2d696441a11760429cd9845bd84987b9313242","from_asset":"native","to_asset":"0x87b723960c170561e6b7cb74188b5f159e272c74","from_amount":"0x470de4df820000","to_amount":"0x22db8e23bcaee","from_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_I603","to_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_T250","from_network":"eth","to_network":"eth","from_is_supported_asset":true,"to_is_supported_asset":false,"to_asset_symbol":"KAISER","to_asset_decimals":9,"from_amount_fiat_values":[{"code":"usd","value":60.0}]}"""


{-| The enriched row turned around: a token goes in and the native coin comes
out, so the curated symbol and decimals sit on the from leg. USDT's are the
curated list's own; the to leg, native, carries none. The leg transfers are
swapped to match (the token leg is a `_T` transfer, the native one a trace).
-}
tokenInputDexSwap : String
tokenInputDexSwap =
    """{"conversion_type":"dex_swap","from_address":"0x4c2d696441a11760429cd9845bd84987b9313242","to_address":"0x4c2d696441a11760429cd9845bd84987b9313242","from_asset":"0xdac17f958d2ee523a2206206994597c13d831ec7","to_asset":"native","from_amount":"0x470de4df820000","to_amount":"0x22db8e23bcaee","from_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_T250","to_asset_transfer":"0xf5ba2f81943a2f79085667593c83e95a38764ccece331f9eeeef00ca697c7246_I603","from_network":"eth","to_network":"eth","from_is_supported_asset":true,"to_is_supported_asset":true,"from_asset_symbol":"USDT","from_asset_decimals":6,"from_amount_fiat_values":[{"code":"usd","value":60.0}]}"""


legMetadata :
    Api.Data.ExternalConversion
    -> { fromAssetSymbol : Maybe String, fromAssetDecimals : Maybe Int, toAssetSymbol : Maybe String, toAssetDecimals : Maybe Int }
legMetadata c =
    { fromAssetSymbol = c.fromAssetSymbol
    , fromAssetDecimals = c.fromAssetDecimals
    , toAssetSymbol = c.toAssetSymbol
    , toAssetDecimals = c.toAssetDecimals
    }


{-| The same body from a serializer that keeps nulls instead of dropping them.
-}
txlessAddressWithNulls : String
txlessAddressWithNulls =
    """{"currency":"eth","address":"0xab","entity":1,"cluster":1,"status":"clean","balance":{"value":0,"fiat_values":[]},"total_received":{"value":0,"fiat_values":[]},"total_spent":{"value":0,"fiat_values":[]},"in_degree":0,"out_degree":0,"no_incoming_txs":0,"no_outgoing_txs":0,"first_tx":null,"last_tx":null}"""
