module Api.DecoderContractTest exposing (suite)

{-| The generated `Api.Data` decoders are a snapshot of the OpenAPI spec taken
whenever someone last ran `make openapi`. The backend keeps moving. When the
two drift apart nothing fails loudly — a renamed or newly-required field just
makes a decoder reject the whole response, and the UI shows an empty panel.

These tests feed every decoder the response example the spec itself documents
(see `tests/Fixtures/Api.elm`, generated by `tools/gen_api_fixtures.mjs`). A
failure here means "the client no longer understands what the API says it
returns" — regenerate the client, or pin the fixture corpus deliberately.

-}

import Api.Data
import Dict
import Expect
import Fixtures.Api as Fixture
import Json.Decode exposing (Decoder)
import Test exposing (Test, describe, test)


{-| A fixture the client currently cannot decode, together with the field it
trips over.

This asserts the _failure_, so the entry cannot rot: the day the client is
regenerated (or the spec example is completed) this test fails and forces
somebody to look at it — the same idea as `review/suppressed/`.

-}
knownDrift : String -> String -> Decoder a -> String -> Test
knownDrift name missingField decoder json =
    test (name ++ " (known drift: missing " ++ missingField ++ ")") <|
        \_ ->
            case Json.Decode.decodeString decoder json of
                Ok _ ->
                    Expect.fail
                        (name
                            ++ " decodes again — the drift on `"
                            ++ missingField
                            ++ "` is gone. Move it up to the `decodes` list."
                        )

                Err error ->
                    Json.Decode.errorToString error
                        |> String.contains missingField
                        |> Expect.equal True
                        |> Expect.onFail
                            ("expected "
                                ++ name
                                ++ " to fail on the missing `"
                                ++ missingField
                                ++ "`, but it failed differently:\n"
                                ++ Json.Decode.errorToString error
                            )


{-| Decoding must succeed _and_ the error must be readable when it does not.
-}
decodes : String -> Decoder a -> String -> Test
decodes name decoder json =
    test name <|
        \_ ->
            case Json.Decode.decodeString decoder json of
                Ok _ ->
                    Expect.pass

                Err error ->
                    Expect.fail
                        ("the spec example for "
                            ++ name
                            ++ " no longer decodes (spec "
                            ++ Fixture.specVersion
                            ++ "):\n"
                            ++ Json.Decode.errorToString error
                        )


suite : Test
suite =
    describe "Api.Data decoders accept the documented responses"
        [ describe "every spec example decodes"
            [ decodes "address" Api.Data.addressDecoder Fixture.address
            , decodes "address_tx_utxo" Api.Data.addressTxUtxoDecoder Fixture.addressTxUtxo
            , decodes "address_txs" Api.Data.addressTxsDecoder Fixture.addressTxs
            , decodes "block" Api.Data.blockDecoder Fixture.block
            , decodes "block_at_date" Api.Data.blockAtDateDecoder Fixture.blockAtDate
            , decodes "cluster" Api.Data.clusterDecoder Fixture.cluster
            , decodes "currency_stats" Api.Data.currencyStatsDecoder Fixture.currencyStats
            , decodes "entity" Api.Data.clusterDecoder Fixture.entity
            , decodes "link_utxo" Api.Data.linkUtxoDecoder Fixture.linkUtxo
            , decodes "links" Api.Data.linksDecoder Fixture.links
            , decodes "neighbor_address" Api.Data.neighborAddressDecoder Fixture.neighborAddress
            , decodes "neighbor_cluster" Api.Data.neighborClusterDecoder Fixture.neighborCluster
            , decodes "rate" Api.Data.rateDecoder Fixture.rate
            , decodes "rates" Api.Data.ratesDecoder Fixture.rates
            , decodes "search_result" Api.Data.searchResultDecoder Fixture.searchResult
            , decodes "search_result_by_currency" Api.Data.searchResultByCurrencyDecoder Fixture.searchResultByCurrency
            , decodes "tag_summary" Api.Data.tagSummaryDecoder Fixture.tagSummary
            , decodes "token_config" Api.Data.tokenConfigDecoder Fixture.tokenConfig
            , decodes "token_configs" Api.Data.tokenConfigsDecoder Fixture.tokenConfigs
            , decodes "tx_account" Api.Data.txAccountDecoder Fixture.txAccount
            , decodes "tx_ref" Api.Data.txRefDecoder Fixture.txRef
            , decodes "tx_summary" Api.Data.txSummaryDecoder Fixture.txSummary
            , decodes "tx_utxo" Api.Data.txUtxoDecoder Fixture.txUtxo
            , decodes "tx_value" Api.Data.txValueDecoder Fixture.txValue
            , decodes "values" Api.Data.valuesDecoder Fixture.values
            ]
        , describe "known drift between the client and the spec"
            -- The generated client declares these fields required while the
            -- current spec (2.15.0) neither marks them required nor puts them in
            -- its own response example. If the API really omits one, the whole
            -- response is rejected and the panel stays empty — worth confirming
            -- against a live instance and then either regenerating the client or
            -- completing the spec upstream.
            [ knownDrift "address_tag" "tag_type" Api.Data.addressTagDecoder Fixture.addressTag
            , knownDrift "address_tags" "tag_type" Api.Data.addressTagsDecoder Fixture.addressTags
            , knownDrift "stats" "request_timestamp" Api.Data.statsDecoder Fixture.stats
            ]
        , describe "the fields the UI reads actually arrive"
            -- Decoding to a record full of Nothings would still pass above, so
            -- spot-check the values the Pathfinder views and tables depend on.
            [ test "an address carries balance, cluster id and tx counts" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.addressDecoder Fixture.address
                        |> Result.map
                            (\a ->
                                { address = a.address
                                , currency = a.currency
                                , cluster = a.cluster
                                , balance = a.balance.value
                                , noIncomingTxs = a.noIncomingTxs
                                , noOutgoingTxs = a.noOutgoingTxs
                                , fiatCodes = a.balance.fiatValues |> List.map .code
                                }
                            )
                        |> Expect.equal
                            (Ok
                                { address = "1Archive1n2C579dMsAu3iC6tWzuQJz8dN"
                                , currency = "btc"
                                , cluster = 264711
                                , balance = 1000000
                                , noIncomingTxs = 200
                                , noOutgoingTxs = 100
                                , fiatCodes = [ "eur", "usd" ]
                                }
                            )
            , test "a utxo transaction carries its inputs and outputs" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.txUtxoDecoder Fixture.txUtxo
                        |> Result.map
                            (\tx ->
                                ( tx.txHash
                                , tx.inputs |> Maybe.map List.length
                                , tx.outputs |> Maybe.map List.length
                                )
                            )
                        |> Result.map (\( hash, i, o ) -> ( hash /= "", i /= Just 0, o /= Just 0 ))
                        |> Expect.equal (Ok ( True, True, True ))
            , test "an account transaction carries its value and endpoints" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.txAccountDecoder Fixture.txAccount
                        |> Result.map (\tx -> ( tx.fromAddress /= "", tx.toAddress /= "", tx.value.value ))
                        |> Result.map (\( f, t, v ) -> ( f, t, v > 0 ))
                        |> Expect.equal (Ok ( True, True, True ))
            , test "a neighbor carries the address it points at and the value moved" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.neighborAddressDecoder Fixture.neighborAddress
                        |> Result.map (\n -> ( n.address.address /= "", n.noTxs > 0 ))
                        |> Expect.equal (Ok ( True, True ))
            , test "a tag summary carries the labels and counts the tag panel shows" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.tagSummaryDecoder Fixture.tagSummary
                        |> Result.map
                            (\t ->
                                ( t.tagCount > 0
                                , t.broadCategory /= ""
                                , Dict.isEmpty t.labelSummary
                                )
                            )
                        |> Expect.equal (Ok ( True, True, False ))
            , test "token configs carry ticker and decimals, which drive every token amount" <|
                \_ ->
                    Json.Decode.decodeString Api.Data.tokenConfigsDecoder Fixture.tokenConfigs
                        |> Result.map
                            (.tokenConfigs
                                >> List.map (\c -> ( c.ticker /= "", c.decimals > 0 ))
                            )
                        |> Result.map (List.all (\( a, b ) -> a && b))
                        |> Expect.equal (Ok True)
            ]
        ]
