{-
   GraphSense API
   GraphSense API

   The version of the OpenAPI document: 0.5.2

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Bulk exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


type Operation
    = OperationGetBlock
    | OperationListBlockTxs
    | OperationGetAddress
    | OperationListAddressTxs
    | OperationListTagsByAddress
    | OperationListAddressNeighbors
    | OperationGetAddressEntity
    | OperationListAddressLinks
    | OperationGetEntity
    | OperationListTagsByEntity
    | OperationListEntityNeighbors
    | OperationListEntityTxs
    | OperationListEntityLinks
    | OperationListEntityAddresses
    | OperationGetTx
    | OperationGetTxIo
    | OperationGetExchangeRates


operationVariants : List Operation
operationVariants =
    [ OperationGetBlock
    , OperationListBlockTxs
    , OperationGetAddress
    , OperationListAddressTxs
    , OperationListTagsByAddress
    , OperationListAddressNeighbors
    , OperationGetAddressEntity
    , OperationListAddressLinks
    , OperationGetEntity
    , OperationListTagsByEntity
    , OperationListEntityNeighbors
    , OperationListEntityTxs
    , OperationListEntityLinks
    , OperationListEntityAddresses
    , OperationGetTx
    , OperationGetTxIo
    , OperationGetExchangeRates
    ]


stringFromOperation : Operation -> String
stringFromOperation model =
    case model of
        OperationGetBlock ->
            "get_block"

        OperationListBlockTxs ->
            "list_block_txs"

        OperationGetAddress ->
            "get_address"

        OperationListAddressTxs ->
            "list_address_txs"

        OperationListTagsByAddress ->
            "list_tags_by_address"

        OperationListAddressNeighbors ->
            "list_address_neighbors"

        OperationGetAddressEntity ->
            "get_address_entity"

        OperationListAddressLinks ->
            "list_address_links"

        OperationGetEntity ->
            "get_entity"

        OperationListTagsByEntity ->
            "list_tags_by_entity"

        OperationListEntityNeighbors ->
            "list_entity_neighbors"

        OperationListEntityTxs ->
            "list_entity_txs"

        OperationListEntityLinks ->
            "list_entity_links"

        OperationListEntityAddresses ->
            "list_entity_addresses"

        OperationGetTx ->
            "get_tx"

        OperationGetTxIo ->
            "get_tx_io"

        OperationGetExchangeRates ->
            "get_exchange_rates"


makeOperationFromString : String -> Maybe Operation
makeOperationFromString str =
    case str of
    "get_block" ->
        Just OperationGetBlock

    "list_block_txs" ->
        Just OperationListBlockTxs

    "get_address" ->
        Just OperationGetAddress

    "list_address_txs" ->
        Just OperationListAddressTxs

    "list_tags_by_address" ->
        Just OperationListTagsByAddress

    "list_address_neighbors" ->
        Just OperationListAddressNeighbors

    "get_address_entity" ->
        Just OperationGetAddressEntity

    "list_address_links" ->
        Just OperationListAddressLinks

    "get_entity" ->
        Just OperationGetEntity

    "list_tags_by_entity" ->
        Just OperationListTagsByEntity

    "list_entity_neighbors" ->
        Just OperationListEntityNeighbors

    "list_entity_txs" ->
        Just OperationListEntityTxs

    "list_entity_links" ->
        Just OperationListEntityLinks

    "list_entity_addresses" ->
        Just OperationListEntityAddresses

    "get_tx" ->
        Just OperationGetTx

    "get_tx_io" ->
        Just OperationGetTxIo

    "get_exchange_rates" ->
        Just OperationGetExchangeRates

    _ ->
        Nothing





type Operation
    = OperationGetBlock
    | OperationListBlockTxs
    | OperationGetAddress
    | OperationListAddressTxs
    | OperationListTagsByAddress
    | OperationListAddressNeighbors
    | OperationGetAddressEntity
    | OperationListAddressLinks
    | OperationGetEntity
    | OperationListTagsByEntity
    | OperationListEntityNeighbors
    | OperationListEntityTxs
    | OperationListEntityLinks
    | OperationListEntityAddresses
    | OperationGetTx
    | OperationGetTxIo
    | OperationGetExchangeRates


operationVariants : List Operation
operationVariants =
    [ OperationGetBlock
    , OperationListBlockTxs
    , OperationGetAddress
    , OperationListAddressTxs
    , OperationListTagsByAddress
    , OperationListAddressNeighbors
    , OperationGetAddressEntity
    , OperationListAddressLinks
    , OperationGetEntity
    , OperationListTagsByEntity
    , OperationListEntityNeighbors
    , OperationListEntityTxs
    , OperationListEntityLinks
    , OperationListEntityAddresses
    , OperationGetTx
    , OperationGetTxIo
    , OperationGetExchangeRates
    ]


stringFromOperation : Operation -> String
stringFromOperation model =
    case model of
        OperationGetBlock ->
            "get_block"

        OperationListBlockTxs ->
            "list_block_txs"

        OperationGetAddress ->
            "get_address"

        OperationListAddressTxs ->
            "list_address_txs"

        OperationListTagsByAddress ->
            "list_tags_by_address"

        OperationListAddressNeighbors ->
            "list_address_neighbors"

        OperationGetAddressEntity ->
            "get_address_entity"

        OperationListAddressLinks ->
            "list_address_links"

        OperationGetEntity ->
            "get_entity"

        OperationListTagsByEntity ->
            "list_tags_by_entity"

        OperationListEntityNeighbors ->
            "list_entity_neighbors"

        OperationListEntityTxs ->
            "list_entity_txs"

        OperationListEntityLinks ->
            "list_entity_links"

        OperationListEntityAddresses ->
            "list_entity_addresses"

        OperationGetTx ->
            "get_tx"

        OperationGetTxIo ->
            "get_tx_io"

        OperationGetExchangeRates ->
            "get_exchange_rates"


makeOperationFromString : String -> Maybe Operation
makeOperationFromString str =
    case str of
    "get_block" ->
        Just OperationGetBlock

    "list_block_txs" ->
        Just OperationListBlockTxs

    "get_address" ->
        Just OperationGetAddress

    "list_address_txs" ->
        Just OperationListAddressTxs

    "list_tags_by_address" ->
        Just OperationListTagsByAddress

    "list_address_neighbors" ->
        Just OperationListAddressNeighbors

    "get_address_entity" ->
        Just OperationGetAddressEntity

    "list_address_links" ->
        Just OperationListAddressLinks

    "get_entity" ->
        Just OperationGetEntity

    "list_tags_by_entity" ->
        Just OperationListTagsByEntity

    "list_entity_neighbors" ->
        Just OperationListEntityNeighbors

    "list_entity_txs" ->
        Just OperationListEntityTxs

    "list_entity_links" ->
        Just OperationListEntityLinks

    "list_entity_addresses" ->
        Just OperationListEntityAddresses

    "get_tx" ->
        Just OperationGetTx

    "get_tx_io" ->
        Just OperationGetTxIo

    "get_exchange_rates" ->
        Just OperationGetExchangeRates

    _ ->
        Nothing






bulkCsv : (String) -> (Operation) -> (Int) -> (Object) -> Api.Request String
bulkCsv currency_path operation_path numPages_query body_body =
    Api.request
        "POST"
        "/{currency}/bulk.csv/{operation}"
        [ ( "currency", identity currency_path ), ( "operation", stringFromOperation operation_path ) ]
        [ ( "num_pages", Just <| (String.fromInt) numPages_query ) ]
        []
        (Just (encodeObject body_body))
        Json.Decode.string



bulkJson : (String) -> (Operation) -> (Int) -> (Object) -> Api.Request (List AnyType)
bulkJson currency_path operation_path numPages_query body_body =
    Api.request
        "POST"
        "/{currency}/bulk.json/{operation}"
        [ ( "currency", identity currency_path ), ( "operation", stringFromOperation operation_path ) ]
        [ ( "num_pages", Just <| (String.fromInt) numPages_query ) ]
        []
        (Just (encodeObject body_body))
        (Json.Decode.list (Json.Decode.dict Api.Data.anyTypeDecoderApi.Data.anyTypeDecoder))

