{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   The version of the OpenAPI document: 1.7.0
   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Experimental exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getTagSummaryByAddress : (String) -> (String) -> Maybe (Bool) -> Api.Request Api.Data.TagSummary
getTagSummaryByAddress currency_path address_path includeBestClusterTag_query =
    Api.request
        "GET"
        "/{currency}/addresses/{address}/tag_summary"
        [ ( "currency", identity currency_path ), ( "address", identity address_path ) ]
        [ ( "include_best_cluster_tag", Maybe.map ((\val -> if val then "true" else "false")) includeBestClusterTag_query ) ]
        []
        Nothing
        Api.Data.tagSummaryDecoder



getTagSummaryByEntity : (String) -> (Int) -> Api.Request Api.Data.TagSummary
getTagSummaryByEntity currency_path entity_path =
    Api.request
        "GET"
        "/{currency}/entities/{entity}/tag_summary"
        [ ( "currency", identity currency_path ), ( "entity", String.fromInt entity_path ) ]
        []
        []
        Nothing
        Api.Data.tagSummaryDecoder

