{-
   GraphSense API
   GraphSense API

   The version of the OpenAPI document: 0.5.2

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.General exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getStatistics : Api.Request Api.Data.Stats
getStatistics =
    Api.request
        "GET"
        "/stats"
        []
        []
        []
        Nothing
        Api.Data.statsDecoder



search : (String) -> Maybe (String) -> Maybe (Int) -> Api.Request Api.Data.SearchResult
search q_query currency_query limit_query =
    Api.request
        "GET"
        "/search"
        []
        [ ( "currency", Maybe.map (identity) currency_query ), ( "q", Just <| (identity) q_query ), ( "limit", Maybe.map (String.fromInt) limit_query ) ]
        []
        Nothing
        Api.Data.searchResultDecoder

