{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.General exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getStatistics : Api.Request Api.Data.Stats
getStatistics =
    Api.request
        "GET"
        "/stats"
        []
        []
        []
        Nothing
        Api.Data.statsDecoder



search : (String) -> Maybe (String) -> Maybe (Int) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Bool) -> Api.Request Api.Data.SearchResult
search q_query currency_query limit_query includeSubTxIdentifiers_query includeLabels_query includeActors_query includeTxs_query includeAddresses_query =
    Api.request
        "GET"
        "/search"
        []
        [ ( "currency", Maybe.map (identity) currency_query ), ( "q", Just <| (identity) q_query ), ( "limit", Maybe.map (String.fromInt) limit_query ), ( "include_sub_tx_identifiers", Maybe.map ((\val -> if val then "true" else "false")) includeSubTxIdentifiers_query ), ( "include_labels", Maybe.map ((\val -> if val then "true" else "false")) includeLabels_query ), ( "include_actors", Maybe.map ((\val -> if val then "true" else "false")) includeActors_query ), ( "include_txs", Maybe.map ((\val -> if val then "true" else "false")) includeTxs_query ), ( "include_addresses", Maybe.map ((\val -> if val then "true" else "false")) includeAddresses_query ) ]
        []
        Nothing
        Api.Data.searchResultDecoder

