{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   The version of the OpenAPI document: 1.1.1
   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Rates exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



getExchangeRates : (String) -> (Int) -> Api.Request Api.Data.Rates
getExchangeRates currency_path height_path =
    Api.request
        "GET"
        "/{currency}/rates/{height}"
        [ ( "currency", identity currency_path ), ( "height", String.fromInt height_path ) ]
        []
        []
        Nothing
        Api.Data.ratesDecoder

