{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   The version of the OpenAPI document: 1.0.1
   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Tags exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode



listAddressTags : (String) -> Maybe (String) -> Maybe (Int) -> Api.Request Api.Data.AddressTags
listAddressTags label_query page_query pagesize_query =
    Api.request
        "GET"
        "/tags"
        []
        [ ( "label", Just <| (identity) label_query ), ( "page", Maybe.map (identity) page_query ), ( "pagesize", Maybe.map (String.fromInt) pagesize_query ) ]
        []
        Nothing
        Api.Data.addressTagsDecoder



listConcepts : (String) -> Api.Request (List Api.Data.Concept)
listConcepts taxonomy_path =
    Api.request
        "GET"
        "/tags/taxonomies/{taxonomy}/concepts"
        [ ( "taxonomy", identity taxonomy_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.conceptDecoder)



listTaxonomies : Api.Request (List Api.Data.Taxonomy)
listTaxonomies =
    Api.request
        "GET"
        "/tags/taxonomies"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.taxonomyDecoder)

