{-
   GraphSense API
   GraphSense API

   The version of the OpenAPI document: 0.5.2

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Tags exposing
    ( listConcepts
    , listTags, Level(..), levelVariants
    , listTaxonomies
    )

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


type Level
    = LevelAddress
    | LevelEntity


levelVariants : List Level
levelVariants =
    [ LevelAddress
    , LevelEntity
    ]


stringFromLevel : Level -> String
stringFromLevel model =
    case model of
        LevelAddress ->
            "address"

        LevelEntity ->
            "entity"





listConcepts : String -> Api.Request (List Api.Data.Concept)
listConcepts taxonomy_path =
    Api.request
        "GET"
        "/tags/taxonomies/{taxonomy}/concepts"
        [ ( "taxonomy", identity taxonomy_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.conceptDecoder)



listTags : String -> String -> Level -> Maybe String -> Maybe Int -> Api.Request Api.Data.Tags
listTags currency_path label_query level_query page_query pagesize_query =
    Api.request
        "GET"
        "/{currency}/tags"
        [ ( "currency", identity currency_path ) ]
        [ ( "label", Just <| identity label_query ), ( "level", Just <| stringFromLevel level_query ), ( "page", Maybe.map identity page_query ), ( "pagesize", Maybe.map String.fromInt pagesize_query ) ]
        []
        Nothing
        Api.Data.tagsDecoder



listTaxonomies : Api.Request (List Api.Data.Taxonomy)
listTaxonomies =
    Api.request
        "GET"
        "/tags/taxonomies"
        []
        []
        []
        Nothing
        (Json.Decode.list Api.Data.taxonomyDecoder)
