{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   The version of the OpenAPI document: 1.3.0
   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Tokens exposing (..)

import Api
import Api.Data


listSupportedTokens : String -> Api.Request Api.Data.TokenConfigs
listSupportedTokens currency_path =
    Api.request
        "GET"
        "/{currency}/supported_tokens"
        [ ( "currency", identity currency_path ) ]
        []
        []
        Nothing
        Api.Data.tokenConfigsDecoder
