{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   The version of the OpenAPI document: 2.0.0a7
   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Txs exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


type Io
    = IoInputs
    | IoOutputs


ioVariants : List Io
ioVariants =
    [ IoInputs
    , IoOutputs
    ]


stringFromIo : Io -> String
stringFromIo model =
    case model of
        IoInputs ->
            "inputs"

        IoOutputs ->
            "outputs"


makeIoFromString : String -> Maybe Io
makeIoFromString str =
    case str of
    "inputs" ->
        Just IoInputs

    "outputs" ->
        Just IoOutputs

    _ ->
        Nothing






getSpendingTxs : (String) -> (String) -> Maybe (Int) -> Api.Request (List Api.Data.TxRef)
getSpendingTxs currency_path txHash_path ioIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/spending"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "io_index", Maybe.map (String.fromInt) ioIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txRefDecoder)



getSpentInTxs : (String) -> (String) -> Maybe (Int) -> Api.Request (List Api.Data.TxRef)
getSpentInTxs currency_path txHash_path ioIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/spent_in"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "io_index", Maybe.map (String.fromInt) ioIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txRefDecoder)



getTx : (String) -> (String) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Int) -> Api.Request Api.Data.Tx
getTx currency_path txHash_path includeIo_query includeNonstandardIo_query includeIoIndex_query tokenTxId_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "include_io", Maybe.map ((\val -> if val then "true" else "false")) includeIo_query ), ( "include_nonstandard_io", Maybe.map ((\val -> if val then "true" else "false")) includeNonstandardIo_query ), ( "include_io_index", Maybe.map ((\val -> if val then "true" else "false")) includeIoIndex_query ), ( "token_tx_id", Maybe.map (String.fromInt) tokenTxId_query ) ]
        []
        Nothing
        Api.Data.txDecoder



getTxIo : (String) -> (String) -> (Io) -> Maybe (Bool) -> Maybe (Bool) -> Api.Request (List Api.Data.TxValue)
getTxIo currency_path txHash_path io_path includeNonstandardIo_query includeIoIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/{io}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ), ( "io", stringFromIo io_path ) ]
        [ ( "include_nonstandard_io", Maybe.map ((\val -> if val then "true" else "false")) includeNonstandardIo_query ), ( "include_io_index", Maybe.map ((\val -> if val then "true" else "false")) includeIoIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txValueDecoder)



listTokenTxs : (String) -> (String) -> Api.Request (List Api.Data.TxAccount)
listTokenTxs currency_path txHash_path =
    Api.request
        "GET"
        "/{currency}/token_txs/{txHash}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.txAccountDecoder)

