{-
   GraphSense API
   GraphSense API provides programmatic access to various ledgers' addresses, entities, blocks, transactions and tags for automated and highly efficient forensics tasks.

   Contact: contact@ikna.io

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git

   DO NOT EDIT THIS FILE MANUALLY.

   For more info on generating Elm code, see https://eriktim.github.io/openapi-elm/
-}


module Api.Request.Txs exposing (..)

import Api
import Api.Data
import Dict
import Http
import Json.Decode
import Json.Encode


type Io
    = IoInputs
    | IoOutputs


ioVariants : List Io
ioVariants =
    [ IoInputs
    , IoOutputs
    ]


stringFromIo : Io -> String
stringFromIo model =
    case model of
        IoInputs ->
            "inputs"

        IoOutputs ->
            "outputs"


makeIoFromString : String -> Maybe Io
makeIoFromString str =
    case str of
    "inputs" ->
        Just IoInputs

    "outputs" ->
        Just IoOutputs

    _ ->
        Nothing



type IncludeHeuristic
    = IncludeHeuristicAll
    | IncludeHeuristicOneTimeChange
    | IncludeHeuristicDirectChange
    | IncludeHeuristicMultiInputChange
    | IncludeHeuristicAllChange
    | IncludeHeuristicAllCoinjoin
    | IncludeHeuristicWhirlpoolCoinjoin
    | IncludeHeuristicWasabiCoinjoin
    | IncludeHeuristicWasabi10Coinjoin
    | IncludeHeuristicWasabi11Coinjoin
    | IncludeHeuristicWasabi20Coinjoin
    | IncludeHeuristicJoinmarketCoinjoin


includeHeuristicVariants : List IncludeHeuristic
includeHeuristicVariants =
    [ IncludeHeuristicAll
    , IncludeHeuristicOneTimeChange
    , IncludeHeuristicDirectChange
    , IncludeHeuristicMultiInputChange
    , IncludeHeuristicAllChange
    , IncludeHeuristicAllCoinjoin
    , IncludeHeuristicWhirlpoolCoinjoin
    , IncludeHeuristicWasabiCoinjoin
    , IncludeHeuristicWasabi10Coinjoin
    , IncludeHeuristicWasabi11Coinjoin
    , IncludeHeuristicWasabi20Coinjoin
    , IncludeHeuristicJoinmarketCoinjoin
    ]


stringFromIncludeHeuristic : IncludeHeuristic -> String
stringFromIncludeHeuristic model =
    case model of
        IncludeHeuristicAll ->
            "all"

        IncludeHeuristicOneTimeChange ->
            "one_time_change"

        IncludeHeuristicDirectChange ->
            "direct_change"

        IncludeHeuristicMultiInputChange ->
            "multi_input_change"

        IncludeHeuristicAllChange ->
            "all_change"

        IncludeHeuristicAllCoinjoin ->
            "all_coinjoin"

        IncludeHeuristicWhirlpoolCoinjoin ->
            "whirlpool_coinjoin"

        IncludeHeuristicWasabiCoinjoin ->
            "wasabi_coinjoin"

        IncludeHeuristicWasabi10Coinjoin ->
            "wasabi_1_0_coinjoin"

        IncludeHeuristicWasabi11Coinjoin ->
            "wasabi_1_1_coinjoin"

        IncludeHeuristicWasabi20Coinjoin ->
            "wasabi_2_0_coinjoin"

        IncludeHeuristicJoinmarketCoinjoin ->
            "joinmarket_coinjoin"


makeIncludeHeuristicFromString : String -> Maybe IncludeHeuristic
makeIncludeHeuristicFromString str =
    case str of
    "all" ->
        Just IncludeHeuristicAll

    "one_time_change" ->
        Just IncludeHeuristicOneTimeChange

    "direct_change" ->
        Just IncludeHeuristicDirectChange

    "multi_input_change" ->
        Just IncludeHeuristicMultiInputChange

    "all_change" ->
        Just IncludeHeuristicAllChange

    "all_coinjoin" ->
        Just IncludeHeuristicAllCoinjoin

    "whirlpool_coinjoin" ->
        Just IncludeHeuristicWhirlpoolCoinjoin

    "wasabi_coinjoin" ->
        Just IncludeHeuristicWasabiCoinjoin

    "wasabi_1_0_coinjoin" ->
        Just IncludeHeuristicWasabi10Coinjoin

    "wasabi_1_1_coinjoin" ->
        Just IncludeHeuristicWasabi11Coinjoin

    "wasabi_2_0_coinjoin" ->
        Just IncludeHeuristicWasabi20Coinjoin

    "joinmarket_coinjoin" ->
        Just IncludeHeuristicJoinmarketCoinjoin

    _ ->
        Nothing






getSpendingTxs : (String) -> (String) -> Maybe (Int) -> Api.Request (List Api.Data.TxRef)
getSpendingTxs currency_path txHash_path ioIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/spending"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "io_index", Maybe.map (String.fromInt) ioIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txRefDecoder)



getSpentInTxs : (String) -> (String) -> Maybe (Int) -> Api.Request (List Api.Data.TxRef)
getSpentInTxs currency_path txHash_path ioIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/spent_in"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "io_index", Maybe.map (String.fromInt) ioIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txRefDecoder)



getTx : (String) -> (String) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (Int) -> Maybe (List IncludeHeuristic) -> Api.Request Api.Data.Tx
getTx currency_path txHash_path includeIo_query includeNonstandardIo_query includeIoIndex_query tokenTxId_query includeHeuristics_query =
    let
        includeHeuristicsParams =
            includeHeuristics_query
                |> Maybe.map (List.map (stringFromIncludeHeuristic >> (\value -> ( "include_heuristics", Just value ))))
                |> Maybe.withDefault []

        queryParams =
            [ ( "include_io", Maybe.map ((\val -> if val then "true" else "false")) includeIo_query )
            , ( "include_nonstandard_io", Maybe.map ((\val -> if val then "true" else "false")) includeNonstandardIo_query )
            , ( "include_io_index", Maybe.map ((\val -> if val then "true" else "false")) includeIoIndex_query )
            , ( "token_tx_id", Maybe.map (String.fromInt) tokenTxId_query )
            ]
                ++ includeHeuristicsParams
    in
    Api.request
        "GET"
        "/{currency}/txs/{txHash}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        queryParams
        []
        Nothing
        Api.Data.txDecoder



getTxConversions : (String) -> (String) -> Api.Request (List Api.Data.ExternalConversion)
getTxConversions currency_path txHash_path =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/conversions"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.externalConversionDecoder)



getTxIo : (String) -> (String) -> (Io) -> Maybe (Bool) -> Maybe (Bool) -> Api.Request (List Api.Data.TxValue)
getTxIo currency_path txHash_path io_path includeNonstandardIo_query includeIoIndex_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/{io}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ), ( "io", stringFromIo io_path ) ]
        [ ( "include_nonstandard_io", Maybe.map ((\val -> if val then "true" else "false")) includeNonstandardIo_query ), ( "include_io_index", Maybe.map ((\val -> if val then "true" else "false")) includeIoIndex_query ) ]
        []
        Nothing
        (Json.Decode.list Api.Data.txValueDecoder)



listTokenTxs : (String) -> (String) -> Api.Request (List Api.Data.TxAccount)
listTokenTxs currency_path txHash_path =
    Api.request
        "GET"
        "/{currency}/token_txs/{txHash}"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        []
        []
        Nothing
        (Json.Decode.list Api.Data.txAccountDecoder)



listTxFlows : (String) -> (String) -> Maybe (Bool) -> Maybe (Bool) -> Maybe (String) -> Maybe (String) -> Maybe (Int) -> Api.Request Api.Data.Txs
listTxFlows currency_path txHash_path stripZeroValueTxs_query onlyTokenTxs_query tokenCurrency_query page_query pagesize_query =
    Api.request
        "GET"
        "/{currency}/txs/{txHash}/flows"
        [ ( "currency", identity currency_path ), ( "txHash", identity txHash_path ) ]
        [ ( "strip_zero_value_txs", Maybe.map ((\val -> if val then "true" else "false")) stripZeroValueTxs_query ), ( "only_token_txs", Maybe.map ((\val -> if val then "true" else "false")) onlyTokenTxs_query ), ( "token_currency", Maybe.map (identity) tokenCurrency_query ), ( "page", Maybe.map (identity) page_query ), ( "pagesize", Maybe.map (String.fromInt) pagesize_query ) ]
        []
        Nothing
        Api.Data.txsDecoder

