module Fixtures.Api exposing (address, addressTag, addressTags, addressTxUtxo, addressTxs, block, blockAtDate, cluster, currencyStats, entity, linkUtxo, links, neighborAddress, neighborCluster, rate, rates, searchResult, searchResultByCurrency, specVersion, stats, tagSummary, tokenConfig, tokenConfigs, txAccount, txRef, txSummary, txUtxo, txValue, values)

{-| GENERATED by `node tools/gen_api_fixtures.mjs` — do not edit by hand.

Response examples taken from the GraphSense OpenAPI spec (<https://api.ikna.io/openapi.json>),
spec version 2.15.0. Each constant is the raw JSON the API documents for
that schema; `tests/Api/DecoderContractTest.elm` feeds them to the generated
`Api.Data` decoders.

-}


{-| The spec version these fixtures were taken from.
-}
specVersion : String
specVersion =
    "2.15.0"


{-| `components.schemas.address.example`
-}
address : String
address =
    "{\"address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"fresh_cluster_id\":264800,\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"status\":\"clean\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.address_tag.example`, plus the field(s) a live instance sends but the example omits (see `EXAMPLE_PATCHES`)
-}
addressTag : String
addressTag =
    "{\"address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"category\":\"organization\",\"cluster\":264711,\"confidence\":\"service_data\",\"confidence_level\":50,\"currency\":\"BTC\",\"entity\":264711,\"is_cluster_definer\":true,\"label\":\"internet archive\",\"lastmod\":1636675200,\"source\":\"https://archive.org/donate/cryptocurrency\",\"tagpack_creator\":\"GraphSense Core Team\",\"tagpack_is_public\":true,\"tagpack_title\":\"GraphSense Demo TagPack\",\"tagpack_uri\":\"https://github.com/graphsense/graphsense-tagpacks/tree/master/packs/demo.yaml\",\"tag_type\":\"actor\"}"


{-| `components.schemas.address_tags.example`, plus the field(s) a live instance sends but the example omits (see `EXAMPLE_PATCHES`)
-}
addressTags : String
addressTags =
    "{\"address_tags\":[{\"address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"category\":\"organization\",\"cluster\":264711,\"confidence\":\"service_data\",\"confidence_level\":50,\"currency\":\"BTC\",\"entity\":264711,\"is_cluster_definer\":true,\"label\":\"internet archive\",\"lastmod\":1636675200,\"source\":\"https://archive.org/donate/cryptocurrency\",\"tagpack_creator\":\"GraphSense Core Team\",\"tagpack_is_public\":true,\"tagpack_title\":\"GraphSense Demo TagPack\",\"tagpack_uri\":\"https://github.com/graphsense/graphsense-tagpacks/tree/master/packs/demo.yaml\",\"tag_type\":\"actor\"}]}"


{-| `components.schemas.address_tx_utxo.example`
-}
addressTxUtxo : String
addressTxUtxo =
    "{\"coinbase\":false,\"currency\":\"btc\",\"height\":690083,\"timestamp\":1625703347,\"tx_hash\":\"0fa34dfc851611b747725f315ea156e2ce931674560f9750ed30be0f786e0d05\",\"tx_type\":\"utxo\",\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":-18.19},{\"code\":\"usd\",\"value\":-21.53}],\"value\":-65485}}"


{-| `components.schemas.address_txs.example`
-}
addressTxs : String
addressTxs =
    "{\"address_txs\":[{\"coinbase\":false,\"currency\":\"btc\",\"height\":690083,\"timestamp\":1625703347,\"tx_hash\":\"0fa34dfc851611b747725f315ea156e2ce931674560f9750ed30be0f786e0d05\",\"tx_type\":\"utxo\",\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":-18.19},{\"code\":\"usd\",\"value\":-21.53}],\"value\":-65485}}],\"next_page\":\"00110004010d329a01010800000000211a20f0f07ffffff5f07ffffff5\"}"


{-| `components.schemas.block.example`
-}
block : String
block =
    "{\"block_hash\":\"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f\",\"currency\":\"btc\",\"height\":47,\"no_txs\":11,\"timestamp\":1231614698}"


{-| `components.schemas.block_at_date.example`
-}
blockAtDate : String
blockAtDate =
    "{\"after_block\":101,\"after_timestamp\":1231614700,\"before_block\":100,\"before_timestamp\":1231614698}"


{-| `components.schemas.cluster.example`
-}
cluster : String
cluster =
    "{\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_address_tags\":3,\"no_addresses\":25,\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"root_address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.currency_stats.example`
-}
currencyStats : String
currencyStats =
    "{\"name\":\"btc\",\"no_address_relations\":1000000,\"no_addresses\":500000,\"no_blocks\":750000,\"no_entities\":200000,\"no_labels\":10000,\"no_tagged_addresses\":5000,\"no_txs\":800000,\"schema_type\":\"utxo\",\"timestamp\":1625703347}"


{-| `components.schemas.entity.example`
-}
entity : String
entity =
    "{\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_address_tags\":3,\"no_addresses\":25,\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"root_address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.link_utxo.example`
-}
linkUtxo : String
linkUtxo =
    "{\"currency\":\"btc\",\"height\":334069,\"input_value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":-6352.06},{\"code\":\"usd\",\"value\":-7916.22}],\"value\":-2278238097},\"output_value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":6630.22},{\"code\":\"usd\",\"value\":8262.87}],\"value\":2378000000},\"timestamp\":1418432879,\"tx_hash\":\"5805ba651d6b72eda3d6e34e43d44c6df20c455f0488acecc75fd6165d6d2590\",\"tx_type\":\"utxo\"}"


{-| `components.schemas.links.example`
-}
links : String
links =
    "{\"links\":[{\"currency\":\"btc\",\"height\":334069,\"input_value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":-6352.06},{\"code\":\"usd\",\"value\":-7916.22}],\"value\":-2278238097},\"output_value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":6630.22},{\"code\":\"usd\",\"value\":8262.87}],\"value\":2378000000},\"timestamp\":1418432879,\"tx_hash\":\"5805ba651d6b72eda3d6e34e43d44c6df20c455f0488acecc75fd6165d6d2590\",\"tx_type\":\"utxo\"}]}"


{-| `components.schemas.neighbor_address.example`
-}
neighborAddress : String
neighborAddress =
    "{\"address\":{\"address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"fresh_cluster_id\":264800,\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"status\":\"clean\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}},\"labels\":[\"internet archive\"],\"no_txs\":5,\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.neighbor_cluster.example`
-}
neighborCluster : String
neighborCluster =
    "{\"cluster\":{\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_address_tags\":3,\"no_addresses\":25,\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"root_address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}},\"entity\":{\"balance\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"cluster\":264711,\"currency\":\"btc\",\"entity\":264711,\"first_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"in_degree\":100,\"last_tx\":{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"},\"no_address_tags\":3,\"no_addresses\":25,\"no_incoming_txs\":200,\"no_outgoing_txs\":100,\"out_degree\":50,\"root_address\":\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"total_received\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_spent\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}},\"labels\":[\"internet archive\"],\"no_txs\":5,\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.rate.example`
-}
rate : String
rate =
    "{\"code\":\"eur\",\"value\":0.1234}"


{-| `components.schemas.rates.example`
-}
rates : String
rates =
    "{\"height\":47,\"rates\":[{\"code\":\"eur\",\"value\":0.1234},{\"code\":\"usd\",\"value\":0.2345}]}"


{-| `components.schemas.search_result.example`
-}
searchResult : String
searchResult =
    "{\"currencies\":[{\"addresses\":[\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"1ArchiveisY6i4Hpostivemate1sVRhQ71\"],\"currency\":\"btc\",\"txs\":[]}],\"labels\":[]}"


{-| `components.schemas.search_result_by_currency.example`
-}
searchResultByCurrency : String
searchResultByCurrency =
    "{\"addresses\":[\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\",\"1ArchiveisY6i4Hpostivemate1sVRhQ71\"],\"currency\":\"btc\",\"txs\":[]}"


{-| `components.schemas.stats.example`, plus the field(s) a live instance sends but the example omits (see `EXAMPLE_PATCHES`)
-}
stats : String
stats =
    "{\"currencies\":[{\"name\":\"btc\",\"no_address_relations\":1000000,\"no_addresses\":500000,\"no_blocks\":750000,\"no_entities\":200000,\"no_labels\":10000,\"no_tagged_addresses\":5000,\"no_txs\":800000,\"schema_type\":\"utxo\",\"timestamp\":1625703347}],\"version\":\"1.0.0\",\"request_timestamp\":\"2026-07-28T00:00:00\"}"


{-| `components.schemas.tag_summary.example`
-}
tagSummary : String
tagSummary =
    "{\"broad_category\":\"organization\",\"concept_tag_cloud\":{\"organization\":{\"cnt\":1,\"weighted\":1}},\"label_summary\":{\"internet archive\":{\"concepts\":[\"organization\"],\"confidence\":0.5,\"count\":1,\"creators\":[\"GraphSense Core Team\"],\"label\":\"internet archive\",\"lastmod\":1636675200,\"relevance\":1,\"sources\":[\"https://archive.org/donate/cryptocurrency\"]}},\"tag_count\":1}"


{-| `components.schemas.token_config.example`
-}
tokenConfig : String
tokenConfig =
    "{\"decimals\":6,\"peg_currency\":\"USD\",\"ticker\":\"USDT\"}"


{-| `components.schemas.token_configs.example`
-}
tokenConfigs : String
tokenConfigs =
    "{\"token_configs\":[{\"decimals\":6,\"peg_currency\":\"USD\",\"ticker\":\"USDT\"},{\"decimals\":18,\"peg_currency\":\"ETH\",\"ticker\":\"WETH\"}]}"


{-| `components.schemas.tx_account.example`
-}
txAccount : String
txAccount =
    "{\"currency\":\"ETH\",\"from_address\":\"addressA\",\"height\":47,\"identifier\":\"eth\",\"network\":\"eth\",\"timestamp\":123456789,\"to_address\":\"addressB\",\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\",\"tx_type\":\"account\",\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}"


{-| `components.schemas.tx_ref.example`
-}
txRef : String
txRef =
    "{\"input_index\":0,\"output_index\":0,\"tx_hash\":\"120439699b10bac37c5316834644acfa8eae6f17b370231e79a2d71ce90f0ebf\"}"


{-| `components.schemas.tx_summary.example`
-}
txSummary : String
txSummary =
    "{\"height\":47,\"timestamp\":123456789,\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\"}"


{-| `components.schemas.tx_utxo.example`
-}
txUtxo : String
txUtxo =
    "{\"coinbase\":false,\"currency\":\"btc\",\"height\":47,\"inputs\":[{\"address\":[\"1Archive1n2C579dMsAu3iC6tWzuQJz8dN\"],\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}},{\"address\":[\"addressB\"],\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}],\"no_inputs\":2,\"no_outputs\":2,\"outputs\":[{\"address\":[\"addressC\"],\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}},{\"address\":[\"addressD\"],\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}}],\"timestamp\":123456789,\"total_input\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"total_output\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000},\"tx_hash\":\"04d92601677d62a985310b61a301e74870fa942c8be0648e16b1db23b996a8cd\",\"tx_type\":\"utxo\"}"


{-| `components.schemas.tx_value.example`
-}
txValue : String
txValue =
    "{\"address\":[\"1GeUZK971B5Umn6JH47PbgrP9qW7RaeW95\"],\"index\":0,\"value\":{\"fiat_values\":[{\"code\":\"eur\",\"value\":19.48},{\"code\":\"usd\",\"value\":25.55}],\"value\":21200000}}"


{-| `components.schemas.values.example`
-}
values : String
values =
    "{\"fiat_values\":[{\"code\":\"eur\",\"value\":10},{\"code\":\"usd\",\"value\":20}],\"value\":1000000}"
