#!/usr/bin/env node
//
// Turns the response examples the GraphSense OpenAPI spec carries into an Elm
// module of raw JSON strings, so `tests/Api/DecoderContractTest.elm` can check
// the generated `Api.Data` decoders against them without network access or an
// API key at test time.
//
// The spec is the contract the backend promises to keep; the generated client
// in openapi/src is a snapshot of it. When the two drift apart the decoders
// start dropping (or rejecting) fields and the UI shows stale or empty data —
// which is exactly what this fixture corpus is meant to catch early.
//
// Usage:
//   node tools/gen_api_fixtures.mjs                        # fetch the live spec
//   node tools/gen_api_fixtures.mjs path/to/openapi.json    # use a local copy
//
// The generated module is committed. Re-run it (and re-run `make test`) after
// every `make openapi`.

import fs from 'fs'
import path from 'path'

const DEFAULT_SPEC = 'https://api.ikna.io/openapi.json'
const OUT = path.join('tests', 'Fixtures', 'Api.elm')

// schema name in the spec -> Elm constant name. Only the payloads the dashboard
// actually decodes; adding one is a one-line change plus a case in the test.
const FIXTURES = {
  address: 'address',
  address_tag: 'addressTag',
  address_tags: 'addressTags',
  address_tx_utxo: 'addressTxUtxo',
  address_txs: 'addressTxs',
  block: 'block',
  block_at_date: 'blockAtDate',
  cluster: 'cluster',
  currency_stats: 'currencyStats',
  entity: 'entity',
  link_utxo: 'linkUtxo',
  links: 'links',
  neighbor_address: 'neighborAddress',
  neighbor_cluster: 'neighborCluster',
  rate: 'rate',
  rates: 'rates',
  search_result: 'searchResult',
  search_result_by_currency: 'searchResultByCurrency',
  stats: 'stats',
  tag_summary: 'tagSummary',
  token_config: 'tokenConfig',
  token_configs: 'tokenConfigs',
  tx_account: 'txAccount',
  tx_ref: 'txRef',
  tx_summary: 'txSummary',
  tx_utxo: 'txUtxo',
  tx_value: 'txValue',
  values: 'values'
}

async function readSpec (source) {
  if (!source) source = DEFAULT_SPEC
  if (/^https?:/.test(source)) {
    const response = await fetch(source)
    if (!response.ok) throw new Error(`${source} responded ${response.status}`)
    return { spec: await response.json(), source }
  }
  return { spec: JSON.parse(fs.readFileSync(source, 'utf8')), source }
}

// Elm has no escape for `"""` inside a triple-quoted string, and the JSON we
// emit is a single line, so a plain quoted string with escapes is simplest.
const elmString = (value) =>
  '"' +
  JSON.stringify(value)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"') +
  '"'

async function main () {
  const { spec, source } = await readSpec(process.argv[2])
  const schemas = spec.components?.schemas || {}

  const missing = Object.keys(FIXTURES).filter(
    (name) => schemas[name]?.example === undefined
  )
  if (missing.length) {
    console.error(
      `error: the spec has no example for: ${missing.join(', ')}\n` +
        'Either the schema was renamed or the example was dropped upstream — ' +
        'update FIXTURES in this script.'
    )
    process.exit(1)
  }

  const entries = Object.entries(FIXTURES)
  const version = spec.info?.version ?? 'unknown'

  const body = entries
    .map(([schema, name]) => {
      return (
        `{-| \`components.schemas.${schema}.example\`\n-}\n` +
        `${name} : String\n${name} =\n    ${elmString(schemas[schema].example)}\n`
      )
    })
    .join('\n\n')

  // elm-format sorts the exposing list; emit it sorted so a plain
  // `make api-fixtures` already produces a formatted file.
  const exposed = ['specVersion', ...entries.map(([, name]) => name)].sort()

  const module = `module Fixtures.Api exposing (${exposed.join(', ')})

{-| GENERATED by \`node tools/gen_api_fixtures.mjs\` — do not edit by hand.

Response examples taken from the GraphSense OpenAPI spec (${/^https?:/.test(source) ? '<' + source + '>' : source}),
spec version ${version}. Each constant is the raw JSON the API documents for
that schema; \`tests/Api/DecoderContractTest.elm\` feeds them to the generated
\`Api.Data\` decoders.

-}


{-| The spec version these fixtures were taken from.
-}
specVersion : String
specVersion =
    "${version}"


${body}`

  fs.mkdirSync(path.dirname(OUT), { recursive: true })
  fs.writeFileSync(OUT, module)
  console.log(`wrote ${OUT}: ${entries.length} fixtures from spec ${version}`)
}

main().catch((error) => {
  console.error(error.message)
  process.exit(1)
})
