-- This module is generated by `setem` command. DO NOT edit manually!


module RecordSetter exposing (..)


s_abbreviation : a -> { b | abbreviation : a } -> { b | abbreviation : a }
s_abbreviation value__ record__ =
    { record__ | abbreviation = value__ }


s_abbreviations : a -> { b | abbreviations : a } -> { b | abbreviations : a }
s_abbreviations value__ record__ =
    { record__ | abbreviations = value__ }


s_absoluteLength : a -> { b | absoluteLength : a } -> { b | absoluteLength : a }
s_absoluteLength value__ record__ =
    { record__ | absoluteLength = value__ }


s_abuse : a -> { b | abuse : a } -> { b | abuse : a }
s_abuse value__ record__ =
    { record__ | abuse = value__ }


s_active : a -> { b | active : a } -> { b | active : a }
s_active value__ record__ =
    { record__ | active = value__ }


s_actual : a -> { b | actual : a } -> { b | actual : a }
s_actual value__ record__ =
    { record__ | actual = value__ }


s_added : a -> { b | added : a } -> { b | added : a }
s_added value__ record__ =
    { record__ | added = value__ }


s_adding : a -> { b | adding : a } -> { b | adding : a }
s_adding value__ record__ =
    { record__ | adding = value__ }


s_addonsNav : a -> { b | addonsNav : a } -> { b | addonsNav : a }
s_addonsNav value__ record__ =
    { record__ | addonsNav = value__ }


s_address : a -> { b | address : a } -> { b | address : a }
s_address value__ record__ =
    { record__ | address = value__ }


s_addressFlags : a -> { b | addressFlags : a } -> { b | addressFlags : a }
s_addressFlags value__ record__ =
    { record__ | addressFlags = value__ }


s_addressFrame : a -> { b | addressFrame : a } -> { b | addressFrame : a }
s_addressFrame value__ record__ =
    { record__ | addressFrame = value__ }


s_addressLabel : a -> { b | addressLabel : a } -> { b | addressLabel : a }
s_addressLabel value__ record__ =
    { record__ | addressLabel = value__ }


s_addressLabelType : a -> { b | addressLabelType : a } -> { b | addressLabelType : a }
s_addressLabelType value__ record__ =
    { record__ | addressLabelType = value__ }


s_addressRect : a -> { b | addressRect : a } -> { b | addressRect : a }
s_addressRect value__ record__ =
    { record__ | addressRect = value__ }


s_addressRoot : a -> { b | addressRoot : a } -> { b | addressRoot : a }
s_addressRoot value__ record__ =
    { record__ | addressRoot = value__ }


s_addressTags : a -> { b | addressTags : a } -> { b | addressTags : a }
s_addressTags value__ record__ =
    { record__ | addressTags = value__ }


s_addressTxs : a -> { b | addressTxs : a } -> { b | addressTxs : a }
s_addressTxs value__ record__ =
    { record__ | addressTxs = value__ }


s_addresses : a -> { b | addresses : a } -> { b | addresses : a }
s_addresses value__ record__ =
    { record__ | addresses = value__ }


s_aliases : a -> { b | aliases : a } -> { b | aliases : a }
s_aliases value__ record__ =
    { record__ | aliases = value__ }


s_alignItems : a -> { b | alignItems : a } -> { b | alignItems : a }
s_alignItems value__ record__ =
    { record__ | alignItems = value__ }


s_alignItemsOrAuto : a -> { b | alignItemsOrAuto : a } -> { b | alignItemsOrAuto : a }
s_alignItemsOrAuto value__ record__ =
    { record__ | alignItemsOrAuto = value__ }


s_all : a -> { b | all : a } -> { b | all : a }
s_all value__ record__ =
    { record__ | all = value__ }


s_allowCookiesFromOtherDomains : a -> { b | allowCookiesFromOtherDomains : a } -> { b | allowCookiesFromOtherDomains : a }
s_allowCookiesFromOtherDomains value__ record__ =
    { record__ | allowCookiesFromOtherDomains = value__ }


s_alpha : a -> { b | alpha : a } -> { b | alpha : a }
s_alpha value__ record__ =
    { record__ | alpha = value__ }


s_angle : a -> { b | angle : a } -> { b | angle : a }
s_angle value__ record__ =
    { record__ | angle = value__ }


s_angleOrDirection : a -> { b | angleOrDirection : a } -> { b | angleOrDirection : a }
s_angleOrDirection value__ record__ =
    { record__ | angleOrDirection = value__ }


s_animation : a -> { b | animation : a } -> { b | animation : a }
s_animation value__ record__ =
    { record__ | animation = value__ }


s_apiKey : a -> { b | apiKey : a } -> { b | apiKey : a }
s_apiKey value__ record__ =
    { record__ | apiKey = value__ }


s_args : a -> { b | args : a } -> { b | args : a }
s_args value__ record__ =
    { record__ | args = value__ }


s_argsMatch : a -> { b | argsMatch : a } -> { b | argsMatch : a }
s_argsMatch value__ record__ =
    { record__ | argsMatch = value__ }


s_attributeNamespace : a -> { b | attributeNamespace : a } -> { b | attributeNamespace : a }
s_attributeNamespace value__ record__ =
    { record__ | attributeNamespace = value__ }


s_auth : a -> { b | auth : a } -> { b | auth : a }
s_auth value__ record__ =
    { record__ | auth = value__ }


s_backgroundAttachment : a -> { b | backgroundAttachment : a } -> { b | backgroundAttachment : a }
s_backgroundAttachment value__ record__ =
    { record__ | backgroundAttachment = value__ }


s_backgroundBlendMode : a -> { b | backgroundBlendMode : a } -> { b | backgroundBlendMode : a }
s_backgroundBlendMode value__ record__ =
    { record__ | backgroundBlendMode = value__ }


s_backgroundClip : a -> { b | backgroundClip : a } -> { b | backgroundClip : a }
s_backgroundClip value__ record__ =
    { record__ | backgroundClip = value__ }


s_backgroundColor : a -> { b | backgroundColor : a } -> { b | backgroundColor : a }
s_backgroundColor value__ record__ =
    { record__ | backgroundColor = value__ }


s_backgroundImage : a -> { b | backgroundImage : a } -> { b | backgroundImage : a }
s_backgroundImage value__ record__ =
    { record__ | backgroundImage = value__ }


s_backgroundOrigin : a -> { b | backgroundOrigin : a } -> { b | backgroundOrigin : a }
s_backgroundOrigin value__ record__ =
    { record__ | backgroundOrigin = value__ }


s_backgroundPosition : a -> { b | backgroundPosition : a } -> { b | backgroundPosition : a }
s_backgroundPosition value__ record__ =
    { record__ | backgroundPosition = value__ }


s_backgroundRepeat : a -> { b | backgroundRepeat : a } -> { b | backgroundRepeat : a }
s_backgroundRepeat value__ record__ =
    { record__ | backgroundRepeat = value__ }


s_backgroundRepeatShorthand : a -> { b | backgroundRepeatShorthand : a } -> { b | backgroundRepeatShorthand : a }
s_backgroundRepeatShorthand value__ record__ =
    { record__ | backgroundRepeatShorthand = value__ }


s_badge : a -> { b | badge : a } -> { b | badge : a }
s_badge value__ record__ =
    { record__ | badge = value__ }


s_bads : a -> { b | bads : a } -> { b | bads : a }
s_bads value__ record__ =
    { record__ | bads = value__ }


s_balance : a -> { b | balance : a } -> { b | balance : a }
s_balance value__ record__ =
    { record__ | balance = value__ }


s_base : a -> { b | base : a } -> { b | base : a }
s_base value__ record__ =
    { record__ | base = value__ }


s_basePath : a -> { b | basePath : a } -> { b | basePath : a }
s_basePath value__ record__ =
    { record__ | basePath = value__ }


s_baseUrl : a -> { b | baseUrl : a } -> { b | baseUrl : a }
s_baseUrl value__ record__ =
    { record__ | baseUrl = value__ }


s_billion : a -> { b | billion : a } -> { b | billion : a }
s_billion value__ record__ =
    { record__ | billion = value__ }


s_binary : a -> { b | binary : a } -> { b | binary : a }
s_binary value__ record__ =
    { record__ | binary = value__ }


s_bits : a -> { b | bits : a } -> { b | bits : a }
s_bits value__ record__ =
    { record__ | bits = value__ }


s_black : a -> { b | black : a } -> { b | black : a }
s_black value__ record__ =
    { record__ | black = value__ }


s_blockAxisOverflow : a -> { b | blockAxisOverflow : a } -> { b | blockAxisOverflow : a }
s_blockAxisOverflow value__ record__ =
    { record__ | blockAxisOverflow = value__ }


s_blockHash : a -> { b | blockHash : a } -> { b | blockHash : a }
s_blockHash value__ record__ =
    { record__ | blockHash = value__ }


s_blue : a -> { b | blue : a } -> { b | blue : a }
s_blue value__ record__ =
    { record__ | blue = value__ }


s_body : a -> { b | body : a } -> { b | body : a }
s_body value__ record__ =
    { record__ | body = value__ }


s_bold : a -> { b | bold : a } -> { b | bold : a }
s_bold value__ record__ =
    { record__ | bold = value__ }


s_boolAttributes : a -> { b | boolAttributes : a } -> { b | boolAttributes : a }
s_boolAttributes value__ record__ =
    { record__ | boolAttributes = value__ }


s_borderCollapse : a -> { b | borderCollapse : a } -> { b | borderCollapse : a }
s_borderCollapse value__ record__ =
    { record__ | borderCollapse = value__ }


s_borderColor : a -> { b | borderColor : a } -> { b | borderColor : a }
s_borderColor value__ record__ =
    { record__ | borderColor = value__ }


s_borderStyle : a -> { b | borderStyle : a } -> { b | borderStyle : a }
s_borderStyle value__ record__ =
    { record__ | borderStyle = value__ }


s_borderWidth : a -> { b | borderWidth : a } -> { b | borderWidth : a }
s_borderWidth value__ record__ =
    { record__ | borderWidth = value__ }


s_bounce : a -> { b | bounce : a } -> { b | bounce : a }
s_bounce value__ record__ =
    { record__ | bounce = value__ }


s_boxSizing : a -> { b | boxSizing : a } -> { b | boxSizing : a }
s_boxSizing value__ record__ =
    { record__ | boxSizing = value__ }


s_branchingBit : a -> { b | branchingBit : a } -> { b | branchingBit : a }
s_branchingBit value__ record__ =
    { record__ | branchingBit = value__ }


s_brandBase : a -> { b | brandBase : a } -> { b | brandBase : a }
s_brandBase value__ record__ =
    { record__ | brandBase = value__ }


s_brandDark : a -> { b | brandDark : a } -> { b | brandDark : a }
s_brandDark value__ record__ =
    { record__ | brandDark = value__ }


s_brandDarker : a -> { b | brandDarker : a } -> { b | brandDarker : a }
s_brandDarker value__ record__ =
    { record__ | brandDarker = value__ }


s_brandLight : a -> { b | brandLight : a } -> { b | brandLight : a }
s_brandLight value__ record__ =
    { record__ | brandLight = value__ }


s_brandLighter : a -> { b | brandLighter : a } -> { b | brandLighter : a }
s_brandLighter value__ record__ =
    { record__ | brandLighter = value__ }


s_brandLightest : a -> { b | brandLightest : a } -> { b | brandLightest : a }
s_brandLightest value__ record__ =
    { record__ | brandLightest = value__ }


s_brandRed : a -> { b | brandRed : a } -> { b | brandRed : a }
s_brandRed value__ record__ =
    { record__ | brandRed = value__ }


s_brandRedLight : a -> { b | brandRedLight : a } -> { b | brandRedLight : a }
s_brandRedLight value__ record__ =
    { record__ | brandRedLight = value__ }


s_brandText : a -> { b | brandText : a } -> { b | brandText : a }
s_brandText value__ record__ =
    { record__ | brandText = value__ }


s_brandWhite : a -> { b | brandWhite : a } -> { b | brandWhite : a }
s_brandWhite value__ record__ =
    { record__ | brandWhite = value__ }


s_breaks : a -> { b | breaks : a } -> { b | breaks : a }
s_breaks value__ record__ =
    { record__ | breaks = value__ }


s_browserHistory : a -> { b | browserHistory : a } -> { b | browserHistory : a }
s_browserHistory value__ record__ =
    { record__ | browserHistory = value__ }


s_button : a -> { b | button : a } -> { b | button : a }
s_button value__ record__ =
    { record__ | button = value__ }


s_bytes : a -> { b | bytes : a } -> { b | bytes : a }
s_bytes value__ record__ =
    { record__ | bytes = value__ }


s_calc : a -> { b | calc : a } -> { b | calc : a }
s_calc value__ record__ =
    { record__ | calc = value__ }


s_caseInsensitive : a -> { b | caseInsensitive : a } -> { b | caseInsensitive : a }
s_caseInsensitive value__ record__ =
    { record__ | caseInsensitive = value__ }


s_category : a -> { b | category : a } -> { b | category : a }
s_category value__ record__ =
    { record__ | category = value__ }


s_changed : a -> { b | changed : a } -> { b | changed : a }
s_changed value__ record__ =
    { record__ | changed = value__ }


s_charsProcessed : a -> { b | charsProcessed : a } -> { b | charsProcessed : a }
s_charsProcessed value__ record__ =
    { record__ | charsProcessed = value__ }


s_charset : a -> { b | charset : a } -> { b | charset : a }
s_charset value__ record__ =
    { record__ | charset = value__ }


s_children : a -> { b | children : a } -> { b | children : a }
s_children value__ record__ =
    { record__ | children = value__ }


s_code : a -> { b | code : a } -> { b | code : a }
s_code value__ record__ =
    { record__ | code = value__ }


s_coinbase : a -> { b | coinbase : a } -> { b | coinbase : a }
s_coinbase value__ record__ =
    { record__ | coinbase = value__ }


s_col : a -> { b | col : a } -> { b | col : a }
s_col value__ record__ =
    { record__ | col = value__ }


s_color : a -> { b | color : a } -> { b | color : a }
s_color value__ record__ =
    { record__ | color = value__ }


s_colorGamut : a -> { b | colorGamut : a } -> { b | colorGamut : a }
s_colorGamut value__ record__ =
    { record__ | colorGamut = value__ }


s_colorScheme : a -> { b | colorScheme : a } -> { b | colorScheme : a }
s_colorScheme value__ record__ =
    { record__ | colorScheme = value__ }


s_colors : a -> { b | colors : a } -> { b | colors : a }
s_colors value__ record__ =
    { record__ | colors = value__ }


s_command : a -> { b | command : a } -> { b | command : a }
s_command value__ record__ =
    { record__ | command = value__ }


s_content : a -> { b | content : a } -> { b | content : a }
s_content value__ record__ =
    { record__ | content = value__ }


s_contentType : a -> { b | contentType : a } -> { b | contentType : a }
s_contentType value__ record__ =
    { record__ | contentType = value__ }


s_context : a -> { b | context : a } -> { b | context : a }
s_context value__ record__ =
    { record__ | context = value__ }


s_contextStack : a -> { b | contextStack : a } -> { b | contextStack : a }
s_contextStack value__ record__ =
    { record__ | contextStack = value__ }


s_css : a -> { b | css : a } -> { b | css : a }
s_css value__ record__ =
    { record__ | css = value__ }


s_currencies : a -> { b | currencies : a } -> { b | currencies : a }
s_currencies value__ record__ =
    { record__ | currencies = value__ }


s_currency : a -> { b | currency : a } -> { b | currency : a }
s_currency value__ record__ =
    { record__ | currency = value__ }


s_currencyBackground : a -> { b | currencyBackground : a } -> { b | currencyBackground : a }
s_currencyBackground value__ record__ =
    { record__ | currencyBackground = value__ }


s_currencyBackgroundPath : a -> { b | currencyBackgroundPath : a } -> { b | currencyBackgroundPath : a }
s_currencyBackgroundPath value__ record__ =
    { record__ | currencyBackgroundPath = value__ }


s_currencyHeading : a -> { b | currencyHeading : a } -> { b | currencyHeading : a }
s_currencyHeading value__ record__ =
    { record__ | currencyHeading = value__ }


s_currentLocation : a -> { b | currentLocation : a } -> { b | currentLocation : a }
s_currentLocation value__ record__ =
    { record__ | currentLocation = value__ }


s_currentModel : a -> { b | currentModel : a } -> { b | currentModel : a }
s_currentModel value__ record__ =
    { record__ | currentModel = value__ }


s_cursor : a -> { b | cursor : a } -> { b | cursor : a }
s_cursor value__ record__ =
    { record__ | cursor = value__ }


s_custom : a -> { b | custom : a } -> { b | custom : a }
s_custom value__ record__ =
    { record__ | custom = value__ }


s_customSuffix : a -> { b | customSuffix : a } -> { b | customSuffix : a }
s_customSuffix value__ record__ =
    { record__ | customSuffix = value__ }


s_danger : a -> { b | danger : a } -> { b | danger : a }
s_danger value__ record__ =
    { record__ | danger = value__ }


s_day : a -> { b | day : a } -> { b | day : a }
s_day value__ record__ =
    { record__ | day = value__ }


s_days : a -> { b | days : a } -> { b | days : a }
s_days value__ record__ =
    { record__ | days = value__ }


s_decimal : a -> { b | decimal : a } -> { b | decimal : a }
s_decimal value__ record__ =
    { record__ | decimal = value__ }


s_decimalSeparator : a -> { b | decimalSeparator : a } -> { b | decimalSeparator : a }
s_decimalSeparator value__ record__ =
    { record__ | decimalSeparator = value__ }


s_decimals : a -> { b | decimals : a } -> { b | decimals : a }
s_decimals value__ record__ =
    { record__ | decimals = value__ }


s_declaration : a -> { b | declaration : a } -> { b | declaration : a }
s_declaration value__ record__ =
    { record__ | declaration = value__ }


s_declarations : a -> { b | declarations : a } -> { b | declarations : a }
s_declarations value__ record__ =
    { record__ | declarations = value__ }


s_decoder : a -> { b | decoder : a } -> { b | decoder : a }
s_decoder value__ record__ =
    { record__ | decoder = value__ }


s_deconstructEffect : a -> { b | deconstructEffect : a } -> { b | deconstructEffect : a }
s_deconstructEffect value__ record__ =
    { record__ | deconstructEffect = value__ }


s_defaultColor : a -> { b | defaultColor : a } -> { b | defaultColor : a }
s_defaultColor value__ record__ =
    { record__ | defaultColor = value__ }


s_defaultHighlighting : a -> { b | defaultHighlighting : a } -> { b | defaultHighlighting : a }
s_defaultHighlighting value__ record__ =
    { record__ | defaultHighlighting = value__ }


s_degree : a -> { b | degree : a } -> { b | degree : a }
s_degree value__ record__ =
    { record__ | degree = value__ }


s_delay : a -> { b | delay : a } -> { b | delay : a }
s_delay value__ record__ =
    { record__ | delay = value__ }


s_delimiters : a -> { b | delimiters : a } -> { b | delimiters : a }
s_delimiters value__ record__ =
    { record__ | delimiters = value__ }


s_descendantsCount : a -> { b | descendantsCount : a } -> { b | descendantsCount : a }
s_descendantsCount value__ record__ =
    { record__ | descendantsCount = value__ }


s_description : a -> { b | description : a } -> { b | description : a }
s_description value__ record__ =
    { record__ | description = value__ }


s_dim : a -> { b | dim : a } -> { b | dim : a }
s_dim value__ record__ =
    { record__ | dim = value__ }


s_disabled : a -> { b | disabled : a } -> { b | disabled : a }
s_disabled value__ record__ =
    { record__ | disabled = value__ }


s_display : a -> { b | display : a } -> { b | display : a }
s_display value__ record__ =
    { record__ | display = value__ }


s_doctype : a -> { b | doctype : a } -> { b | doctype : a }
s_doctype value__ record__ =
    { record__ | doctype = value__ }


s_document : a -> { b | document : a } -> { b | document : a }
s_document value__ record__ =
    { record__ | document = value__ }


s_down : a -> { b | down : a } -> { b | down : a }
s_down value__ record__ =
    { record__ | down = value__ }


s_dragging : a -> { b | dragging : a } -> { b | dragging : a }
s_dragging value__ record__ =
    { record__ | dragging = value__ }


s_duration : a -> { b | duration : a } -> { b | duration : a }
s_duration value__ record__ =
    { record__ | duration = value__ }


s_dx : a -> { b | dx : a } -> { b | dx : a }
s_dx value__ record__ =
    { record__ | dx = value__ }


s_dy : a -> { b | dy : a } -> { b | dy : a }
s_dy value__ record__ =
    { record__ | dy = value__ }


s_effectSimulation : a -> { b | effectSimulation : a } -> { b | effectSimulation : a }
s_effectSimulation value__ record__ =
    { record__ | effectSimulation = value__ }


s_element : a -> { b | element : a } -> { b | element : a }
s_element value__ record__ =
    { record__ | element = value__ }


s_elm : a -> { b | elm : a } -> { b | elm : a }
s_elm value__ record__ =
    { record__ | elm = value__ }


s_end : a -> { b | end : a } -> { b | end : a }
s_end value__ record__ =
    { record__ | end = value__ }


s_ending : a -> { b | ending : a } -> { b | ending : a }
s_ending value__ record__ =
    { record__ | ending = value__ }


s_entities : a -> { b | entities : a } -> { b | entities : a }
s_entities value__ record__ =
    { record__ | entities = value__ }


s_entity : a -> { b | entity : a } -> { b | entity : a }
s_entity value__ record__ =
    { record__ | entity = value__ }


s_entityAddressesCount : a -> { b | entityAddressesCount : a } -> { b | entityAddressesCount : a }
s_entityAddressesCount value__ record__ =
    { record__ | entityAddressesCount = value__ }


s_entityCurrency : a -> { b | entityCurrency : a } -> { b | entityCurrency : a }
s_entityCurrency value__ record__ =
    { record__ | entityCurrency = value__ }


s_entityFlags : a -> { b | entityFlags : a } -> { b | entityFlags : a }
s_entityFlags value__ record__ =
    { record__ | entityFlags = value__ }


s_entityFrame : a -> { b | entityFrame : a } -> { b | entityFrame : a }
s_entityFrame value__ record__ =
    { record__ | entityFrame = value__ }


s_entityLabel : a -> { b | entityLabel : a } -> { b | entityLabel : a }
s_entityLabel value__ record__ =
    { record__ | entityLabel = value__ }


s_entityRect : a -> { b | entityRect : a } -> { b | entityRect : a }
s_entityRect value__ record__ =
    { record__ | entityRect = value__ }


s_entityRoot : a -> { b | entityRoot : a } -> { b | entityRoot : a }
s_entityRoot value__ record__ =
    { record__ | entityRoot = value__ }


s_entityTags : a -> { b | entityTags : a } -> { b | entityTags : a }
s_entityTags value__ record__ =
    { record__ | entityTags = value__ }


s_event : a -> { b | event : a } -> { b | event : a }
s_event value__ record__ =
    { record__ | event = value__ }


s_events : a -> { b | events : a } -> { b | events : a }
s_events value__ record__ =
    { record__ | events = value__ }


s_exactly : a -> { b | exactly : a } -> { b | exactly : a }
s_exactly value__ record__ =
    { record__ | exactly = value__ }


s_expandHandle : a -> { b | expandHandle : a } -> { b | expandHandle : a }
s_expandHandle value__ record__ =
    { record__ | expandHandle = value__ }


s_expandHandlePath : a -> { b | expandHandlePath : a } -> { b | expandHandlePath : a }
s_expandHandlePath value__ record__ =
    { record__ | expandHandlePath = value__ }


s_expandHandleText : a -> { b | expandHandleText : a } -> { b | expandHandleText : a }
s_expandHandleText value__ record__ =
    { record__ | expandHandleText = value__ }


s_expandoModel : a -> { b | expandoModel : a } -> { b | expandoModel : a }
s_expandoModel value__ record__ =
    { record__ | expandoModel = value__ }


s_expandoMsg : a -> { b | expandoMsg : a } -> { b | expandoMsg : a }
s_expandoMsg value__ record__ =
    { record__ | expandoMsg = value__ }


s_expect : a -> { b | expect : a } -> { b | expect : a }
s_expect value__ record__ =
    { record__ | expect = value__ }


s_expected : a -> { b | expected : a } -> { b | expected : a }
s_expected value__ record__ =
    { record__ | expected = value__ }


s_expecting : a -> { b | expecting : a } -> { b | expecting : a }
s_expecting value__ record__ =
    { record__ | expecting = value__ }


s_expiration : a -> { b | expiration : a } -> { b | expiration : a }
s_expiration value__ record__ =
    { record__ | expiration = value__ }


s_exportHistory : a -> { b | exportHistory : a } -> { b | exportHistory : a }
s_exportHistory value__ record__ =
    { record__ | exportHistory = value__ }


s_extra : a -> { b | extra : a } -> { b | extra : a }
s_extra value__ record__ =
    { record__ | extra = value__ }


s_facts : a -> { b | facts : a } -> { b | facts : a }
s_facts value__ record__ =
    { record__ | facts = value__ }


s_feature : a -> { b | feature : a } -> { b | feature : a }
s_feature value__ record__ =
    { record__ | feature = value__ }


s_featureTagValue : a -> { b | featureTagValue : a } -> { b | featureTagValue : a }
s_featureTagValue value__ record__ =
    { record__ | featureTagValue = value__ }


s_fiatValues : a -> { b | fiatValues : a } -> { b | fiatValues : a }
s_fiatValues value__ record__ =
    { record__ | fiatValues = value__ }


s_filename : a -> { b | filename : a } -> { b | filename : a }
s_filename value__ record__ =
    { record__ | filename = value__ }


s_firstTx : a -> { b | firstTx : a } -> { b | firstTx : a }
s_firstTx value__ record__ =
    { record__ | firstTx = value__ }


s_flexBasis : a -> { b | flexBasis : a } -> { b | flexBasis : a }
s_flexBasis value__ record__ =
    { record__ | flexBasis = value__ }


s_flexDirection : a -> { b | flexDirection : a } -> { b | flexDirection : a }
s_flexDirection value__ record__ =
    { record__ | flexDirection = value__ }


s_flexDirectionOrWrap : a -> { b | flexDirectionOrWrap : a } -> { b | flexDirectionOrWrap : a }
s_flexDirectionOrWrap value__ record__ =
    { record__ | flexDirectionOrWrap = value__ }


s_flexWrap : a -> { b | flexWrap : a } -> { b | flexWrap : a }
s_flexWrap value__ record__ =
    { record__ | flexWrap = value__ }


s_flip : a -> { b | flip : a } -> { b | flip : a }
s_flip value__ record__ =
    { record__ | flip = value__ }


s_float : a -> { b | float : a } -> { b | float : a }
s_float value__ record__ =
    { record__ | float = value__ }


s_fontFace : a -> { b | fontFace : a } -> { b | fontFace : a }
s_fontFace value__ record__ =
    { record__ | fontFace = value__ }


s_fontFamily : a -> { b | fontFamily : a } -> { b | fontFamily : a }
s_fontFamily value__ record__ =
    { record__ | fontFamily = value__ }


s_fontSize : a -> { b | fontSize : a } -> { b | fontSize : a }
s_fontSize value__ record__ =
    { record__ | fontSize = value__ }


s_fontStyle : a -> { b | fontStyle : a } -> { b | fontStyle : a }
s_fontStyle value__ record__ =
    { record__ | fontStyle = value__ }


s_fontVariant : a -> { b | fontVariant : a } -> { b | fontVariant : a }
s_fontVariant value__ record__ =
    { record__ | fontVariant = value__ }


s_fontVariantCaps : a -> { b | fontVariantCaps : a } -> { b | fontVariantCaps : a }
s_fontVariantCaps value__ record__ =
    { record__ | fontVariantCaps = value__ }


s_fontVariantLigatures : a -> { b | fontVariantLigatures : a } -> { b | fontVariantLigatures : a }
s_fontVariantLigatures value__ record__ =
    { record__ | fontVariantLigatures = value__ }


s_fontVariantNumeric : a -> { b | fontVariantNumeric : a } -> { b | fontVariantNumeric : a }
s_fontVariantNumeric value__ record__ =
    { record__ | fontVariantNumeric = value__ }


s_fontWeight : a -> { b | fontWeight : a } -> { b | fontWeight : a }
s_fontWeight value__ record__ =
    { record__ | fontWeight = value__ }


s_forAddress : a -> { b | forAddress : a } -> { b | forAddress : a }
s_forAddress value__ record__ =
    { record__ | forAddress = value__ }


s_form : a -> { b | form : a } -> { b | form : a }
s_form value__ record__ =
    { record__ | form = value__ }


s_format_value : a -> { b | format_value : a } -> { b | format_value : a }
s_format_value value__ record__ =
    { record__ | format_value = value__ }


s_found : a -> { b | found : a } -> { b | found : a }
s_found value__ record__ =
    { record__ | found = value__ }


s_foundAny : a -> { b | foundAny : a } -> { b | foundAny : a }
s_foundAny value__ record__ =
    { record__ | foundAny = value__ }


s_frag : a -> { b | frag : a } -> { b | frag : a }
s_frag value__ record__ =
    { record__ | frag = value__ }


s_fragment : a -> { b | fragment : a } -> { b | fragment : a }
s_fragment value__ record__ =
    { record__ | fragment = value__ }


s_frame : a -> { b | frame : a } -> { b | frame : a }
s_frame value__ record__ =
    { record__ | frame = value__ }


s_fromAddress : a -> { b | fromAddress : a } -> { b | fromAddress : a }
s_fromAddress value__ record__ =
    { record__ | fromAddress = value__ }


s_futureTasks : a -> { b | futureTasks : a } -> { b | futureTasks : a }
s_futureTasks value__ record__ =
    { record__ | futureTasks = value__ }


s_getOption : a -> { b | getOption : a } -> { b | getOption : a }
s_getOption value__ record__ =
    { record__ | getOption = value__ }


s_githubFlavored : a -> { b | githubFlavored : a } -> { b | githubFlavored : a }
s_githubFlavored value__ record__ =
    { record__ | githubFlavored = value__ }


s_given : a -> { b | given : a } -> { b | given : a }
s_given value__ record__ =
    { record__ | given = value__ }


s_good : a -> { b | good : a } -> { b | good : a }
s_good value__ record__ =
    { record__ | good = value__ }


s_graph : a -> { b | graph : a } -> { b | graph : a }
s_graph value__ record__ =
    { record__ | graph = value__ }


s_graphRoot : a -> { b | graphRoot : a } -> { b | graphRoot : a }
s_graphRoot value__ record__ =
    { record__ | graphRoot = value__ }


s_green : a -> { b | green : a } -> { b | green : a }
s_green value__ record__ =
    { record__ | green = value__ }


s_grey : a -> { b | grey : a } -> { b | grey : a }
s_grey value__ record__ =
    { record__ | grey = value__ }


s_greyDark : a -> { b | greyDark : a } -> { b | greyDark : a }
s_greyDark value__ record__ =
    { record__ | greyDark = value__ }


s_greyDarker : a -> { b | greyDarker : a } -> { b | greyDarker : a }
s_greyDarker value__ record__ =
    { record__ | greyDarker = value__ }


s_greyDarkest : a -> { b | greyDarkest : a } -> { b | greyDarkest : a }
s_greyDarkest value__ record__ =
    { record__ | greyDarkest = value__ }


s_greyLight : a -> { b | greyLight : a } -> { b | greyLight : a }
s_greyLight value__ record__ =
    { record__ | greyLight = value__ }


s_greyLighter : a -> { b | greyLighter : a } -> { b | greyLighter : a }
s_greyLighter value__ record__ =
    { record__ | greyLighter = value__ }


s_greyLightest : a -> { b | greyLightest : a } -> { b | greyLightest : a }
s_greyLightest value__ record__ =
    { record__ | greyLightest = value__ }


s_hash : a -> { b | hash : a } -> { b | hash : a }
s_hash value__ record__ =
    { record__ | hash = value__ }


s_header : a -> { b | header : a } -> { b | header : a }
s_header value__ record__ =
    { record__ | header = value__ }


s_headerLogo : a -> { b | headerLogo : a } -> { b | headerLogo : a }
s_headerLogo value__ record__ =
    { record__ | headerLogo = value__ }


s_headers : a -> { b | headers : a } -> { b | headers : a }
s_headers value__ record__ =
    { record__ | headers = value__ }


s_heading : a -> { b | heading : a } -> { b | heading : a }
s_heading value__ record__ =
    { record__ | heading = value__ }


s_heading2 : a -> { b | heading2 : a } -> { b | heading2 : a }
s_heading2 value__ record__ =
    { record__ | heading2 = value__ }


s_height : a -> { b | height : a } -> { b | height : a }
s_height value__ record__ =
    { record__ | height = value__ }


s_hex : a -> { b | hex : a } -> { b | hex : a }
s_hex value__ record__ =
    { record__ | hex = value__ }


s_history : a -> { b | history : a } -> { b | history : a }
s_history value__ record__ =
    { record__ | history = value__ }


s_host : a -> { b | host : a } -> { b | host : a }
s_host value__ record__ =
    { record__ | host = value__ }


s_hours : a -> { b | hours : a } -> { b | hours : a }
s_hours value__ record__ =
    { record__ | hours = value__ }


s_hoverCapability : a -> { b | hoverCapability : a } -> { b | hoverCapability : a }
s_hoverCapability value__ record__ =
    { record__ | hoverCapability = value__ }


s_hovercard : a -> { b | hovercard : a } -> { b | hovercard : a }
s_hovercard value__ record__ =
    { record__ | hovercard = value__ }


s_hovercardElement : a -> { b | hovercardElement : a } -> { b | hovercardElement : a }
s_hovercardElement value__ record__ =
    { record__ | hovercardElement = value__ }


s_hovercardRoot : a -> { b | hovercardRoot : a } -> { b | hovercardRoot : a }
s_hovercardRoot value__ record__ =
    { record__ | hovercardRoot = value__ }


s_http : a -> { b | http : a } -> { b | http : a }
s_http value__ record__ =
    { record__ | http = value__ }


s_hue : a -> { b | hue : a } -> { b | hue : a }
s_hue value__ record__ =
    { record__ | hue = value__ }


s_icon : a -> { b | icon : a } -> { b | icon : a }
s_icon value__ record__ =
    { record__ | icon = value__ }


s_id : a -> { b | id : a } -> { b | id : a }
s_id value__ record__ =
    { record__ | id = value__ }


s_importHistory : a -> { b | importHistory : a } -> { b | importHistory : a }
s_importHistory value__ record__ =
    { record__ | importHistory = value__ }


s_import_ : a -> { b | import_ : a } -> { b | import_ : a }
s_import_ value__ record__ =
    { record__ | import_ = value__ }


s_imports : a -> { b | imports : a } -> { b | imports : a }
s_imports value__ record__ =
    { record__ | imports = value__ }


s_inDegree : a -> { b | inDegree : a } -> { b | inDegree : a }
s_inDegree value__ record__ =
    { record__ | inDegree = value__ }


s_inSomeDays : a -> { b | inSomeDays : a } -> { b | inSomeDays : a }
s_inSomeDays value__ record__ =
    { record__ | inSomeDays = value__ }


s_inSomeHours : a -> { b | inSomeHours : a } -> { b | inSomeHours : a }
s_inSomeHours value__ record__ =
    { record__ | inSomeHours = value__ }


s_inSomeMinutes : a -> { b | inSomeMinutes : a } -> { b | inSomeMinutes : a }
s_inSomeMinutes value__ record__ =
    { record__ | inSomeMinutes = value__ }


s_inSomeMonths : a -> { b | inSomeMonths : a } -> { b | inSomeMonths : a }
s_inSomeMonths value__ record__ =
    { record__ | inSomeMonths = value__ }


s_inSomeSeconds : a -> { b | inSomeSeconds : a } -> { b | inSomeSeconds : a }
s_inSomeSeconds value__ record__ =
    { record__ | inSomeSeconds = value__ }


s_inSomeYears : a -> { b | inSomeYears : a } -> { b | inSomeYears : a }
s_inSomeYears value__ record__ =
    { record__ | inSomeYears = value__ }


s_indent : a -> { b | indent : a } -> { b | indent : a }
s_indent value__ record__ =
    { record__ | indent = value__ }


s_index : a -> { b | index : a } -> { b | index : a }
s_index value__ record__ =
    { record__ | index = value__ }


s_infinite : a -> { b | infinite : a } -> { b | infinite : a }
s_infinite value__ record__ =
    { record__ | infinite = value__ }


s_init : a -> { b | init : a } -> { b | init : a }
s_init value__ record__ =
    { record__ | init = value__ }


s_inlineAxisOverflow : a -> { b | inlineAxisOverflow : a } -> { b | inlineAxisOverflow : a }
s_inlineAxisOverflow value__ record__ =
    { record__ | inlineAxisOverflow = value__ }


s_inner : a -> { b | inner : a } -> { b | inner : a }
s_inner value__ record__ =
    { record__ | inner = value__ }


s_input : a -> { b | input : a } -> { b | input : a }
s_input value__ record__ =
    { record__ | input = value__ }


s_inputValue : a -> { b | inputValue : a } -> { b | inputValue : a }
s_inputValue value__ record__ =
    { record__ | inputValue = value__ }


s_inputs : a -> { b | inputs : a } -> { b | inputs : a }
s_inputs value__ record__ =
    { record__ | inputs = value__ }


s_int : a -> { b | int : a } -> { b | int : a }
s_int value__ record__ =
    { record__ | int = value__ }


s_intOrAuto : a -> { b | intOrAuto : a } -> { b | intOrAuto : a }
s_intOrAuto value__ record__ =
    { record__ | intOrAuto = value__ }


s_integers : a -> { b | integers : a } -> { b | integers : a }
s_integers value__ record__ =
    { record__ | integers = value__ }


s_invalid : a -> { b | invalid : a } -> { b | invalid : a }
s_invalid value__ record__ =
    { record__ | invalid = value__ }


s_isClusterDefiner : a -> { b | isClusterDefiner : a } -> { b | isClusterDefiner : a }
s_isClusterDefiner value__ record__ =
    { record__ | isClusterDefiner = value__ }


s_isOutgoing : a -> { b | isOutgoing : a } -> { b | isOutgoing : a }
s_isOutgoing value__ record__ =
    { record__ | isOutgoing = value__ }


s_isPublic : a -> { b | isPublic : a } -> { b | isPublic : a }
s_isPublic value__ record__ =
    { record__ | isPublic = value__ }


s_item : a -> { b | item : a } -> { b | item : a }
s_item value__ record__ =
    { record__ | item = value__ }


s_justifyContent : a -> { b | justifyContent : a } -> { b | justifyContent : a }
s_justifyContent value__ record__ =
    { record__ | justifyContent = value__ }


s_justifyContentOrAuto : a -> { b | justifyContentOrAuto : a } -> { b | justifyContentOrAuto : a }
s_justifyContentOrAuto value__ record__ =
    { record__ | justifyContentOrAuto = value__ }


s_key : a -> { b | key : a } -> { b | key : a }
s_key value__ record__ =
    { record__ | key = value__ }


s_keyframes : a -> { b | keyframes : a } -> { b | keyframes : a }
s_keyframes value__ record__ =
    { record__ | keyframes = value__ }


s_kids : a -> { b | kids : a } -> { b | kids : a }
s_kids value__ record__ =
    { record__ | kids = value__ }


s_label : a -> { b | label : a } -> { b | label : a }
s_label value__ record__ =
    { record__ | label = value__ }


s_labels : a -> { b | labels : a } -> { b | labels : a }
s_labels value__ record__ =
    { record__ | labels = value__ }


s_language : a -> { b | language : a } -> { b | language : a }
s_language value__ record__ =
    { record__ | language = value__ }


s_larger : a -> { b | larger : a } -> { b | larger : a }
s_larger value__ record__ =
    { record__ | larger = value__ }


s_lastEffect : a -> { b | lastEffect : a } -> { b | lastEffect : a }
s_lastEffect value__ record__ =
    { record__ | lastEffect = value__ }


s_lastTx : a -> { b | lastTx : a } -> { b | lastTx : a }
s_lastTx value__ record__ =
    { record__ | lastTx = value__ }


s_lastmod : a -> { b | lastmod : a } -> { b | lastmod : a }
s_lastmod value__ record__ =
    { record__ | lastmod = value__ }


s_latestBlocks : a -> { b | latestBlocks : a } -> { b | latestBlocks : a }
s_latestBlocks value__ record__ =
    { record__ | latestBlocks = value__ }


s_layer : a -> { b | layer : a } -> { b | layer : a }
s_layer value__ record__ =
    { record__ | layer = value__ }


s_layers : a -> { b | layers : a } -> { b | layers : a }
s_layers value__ record__ =
    { record__ | layers = value__ }


s_layout : a -> { b | layout : a } -> { b | layout : a }
s_layout value__ record__ =
    { record__ | layout = value__ }


s_leadingZeros : a -> { b | leadingZeros : a } -> { b | leadingZeros : a }
s_leadingZeros value__ record__ =
    { record__ | leadingZeros = value__ }


s_left : a -> { b | left : a } -> { b | left : a }
s_left value__ record__ =
    { record__ | left = value__ }


s_length : a -> { b | length : a } -> { b | length : a }
s_length value__ record__ =
    { record__ | length = value__ }


s_lengthOrAuto : a -> { b | lengthOrAuto : a } -> { b | lengthOrAuto : a }
s_lengthOrAuto value__ record__ =
    { record__ | lengthOrAuto = value__ }


s_lengthOrAutoOrCoverOrContain : a -> { b | lengthOrAutoOrCoverOrContain : a } -> { b | lengthOrAutoOrCoverOrContain : a }
s_lengthOrAutoOrCoverOrContain value__ record__ =
    { record__ | lengthOrAutoOrCoverOrContain = value__ }


s_lengthOrMinMaxDimension : a -> { b | lengthOrMinMaxDimension : a } -> { b | lengthOrMinMaxDimension : a }
s_lengthOrMinMaxDimension value__ record__ =
    { record__ | lengthOrMinMaxDimension = value__ }


s_lengthOrNone : a -> { b | lengthOrNone : a } -> { b | lengthOrNone : a }
s_lengthOrNone value__ record__ =
    { record__ | lengthOrNone = value__ }


s_lengthOrNoneOrMinMaxDimension : a -> { b | lengthOrNoneOrMinMaxDimension : a } -> { b | lengthOrNoneOrMinMaxDimension : a }
s_lengthOrNoneOrMinMaxDimension value__ record__ =
    { record__ | lengthOrNoneOrMinMaxDimension = value__ }


s_lengthOrNumber : a -> { b | lengthOrNumber : a } -> { b | lengthOrNumber : a }
s_lengthOrNumber value__ record__ =
    { record__ | lengthOrNumber = value__ }


s_lengthOrNumberOrAutoOrNoneOrContent : a -> { b | lengthOrNumberOrAutoOrNoneOrContent : a } -> { b | lengthOrNumberOrAutoOrNoneOrContent : a }
s_lengthOrNumberOrAutoOrNoneOrContent value__ record__ =
    { record__ | lengthOrNumberOrAutoOrNoneOrContent = value__ }


s_lightness : a -> { b | lightness : a } -> { b | lightness : a }
s_lightness value__ record__ =
    { record__ | lightness = value__ }


s_lightnessFactor : a -> { b | lightnessFactor : a } -> { b | lightnessFactor : a }
s_lightnessFactor value__ record__ =
    { record__ | lightnessFactor = value__ }


s_limit : a -> { b | limit : a } -> { b | limit : a }
s_limit value__ record__ =
    { record__ | limit = value__ }


s_links : a -> { b | links : a } -> { b | links : a }
s_links value__ record__ =
    { record__ | links = value__ }


s_listStylePosition : a -> { b | listStylePosition : a } -> { b | listStylePosition : a }
s_listStylePosition value__ record__ =
    { record__ | listStylePosition = value__ }


s_listStyleType : a -> { b | listStyleType : a } -> { b | listStyleType : a }
s_listStyleType value__ record__ =
    { record__ | listStyleType = value__ }


s_listStyleTypeOrPositionOrImage : a -> { b | listStyleTypeOrPositionOrImage : a } -> { b | listStyleTypeOrPositionOrImage : a }
s_listStyleTypeOrPositionOrImage value__ record__ =
    { record__ | listStyleTypeOrPositionOrImage = value__ }


s_loading : a -> { b | loading : a } -> { b | loading : a }
s_loading value__ record__ =
    { record__ | loading = value__ }


s_loadingSpinner : a -> { b | loadingSpinner : a } -> { b | loadingSpinner : a }
s_loadingSpinner value__ record__ =
    { record__ | loadingSpinner = value__ }


s_loadingSpinnerUrl : a -> { b | loadingSpinnerUrl : a } -> { b | loadingSpinnerUrl : a }
s_loadingSpinnerUrl value__ record__ =
    { record__ | loadingSpinnerUrl = value__ }


s_locale : a -> { b | locale : a } -> { b | locale : a }
s_locale value__ record__ =
    { record__ | locale = value__ }


s_logo : a -> { b | logo : a } -> { b | logo : a }
s_logo value__ record__ =
    { record__ | logo = value__ }


s_main : a -> { b | main : a } -> { b | main : a }
s_main value__ record__ =
    { record__ | main = value__ }


s_mapping : a -> { b | mapping : a } -> { b | mapping : a }
s_mapping value__ record__ =
    { record__ | mapping = value__ }


s_markdown : a -> { b | markdown : a } -> { b | markdown : a }
s_markdown value__ record__ =
    { record__ | markdown = value__ }


s_match : a -> { b | match : a } -> { b | match : a }
s_match value__ record__ =
    { record__ | match = value__ }


s_matchingAddresses : a -> { b | matchingAddresses : a } -> { b | matchingAddresses : a }
s_matchingAddresses value__ record__ =
    { record__ | matchingAddresses = value__ }


s_maxHeight : a -> { b | maxHeight : a } -> { b | maxHeight : a }
s_maxHeight value__ record__ =
    { record__ | maxHeight = value__ }


s_maxLettersPerLabelRow : a -> { b | maxLettersPerLabelRow : a } -> { b | maxLettersPerLabelRow : a }
s_maxLettersPerLabelRow value__ record__ =
    { record__ | maxLettersPerLabelRow = value__ }


s_maxWidth : a -> { b | maxWidth : a } -> { b | maxWidth : a }
s_maxWidth value__ record__ =
    { record__ | maxWidth = value__ }


s_message : a -> { b | message : a } -> { b | message : a }
s_message value__ record__ =
    { record__ | message = value__ }


s_messages : a -> { b | messages : a } -> { b | messages : a }
s_messages value__ record__ =
    { record__ | messages = value__ }


s_metadata : a -> { b | metadata : a } -> { b | metadata : a }
s_metadata value__ record__ =
    { record__ | metadata = value__ }


s_method : a -> { b | method : a } -> { b | method : a }
s_method value__ record__ =
    { record__ | method = value__ }


s_million : a -> { b | million : a } -> { b | million : a }
s_million value__ record__ =
    { record__ | million = value__ }


s_minMaxDimension : a -> { b | minMaxDimension : a } -> { b | minMaxDimension : a }
s_minMaxDimension value__ record__ =
    { record__ | minMaxDimension = value__ }


s_minus : a -> { b | minus : a } -> { b | minus : a }
s_minus value__ record__ =
    { record__ | minus = value__ }


s_minutes : a -> { b | minutes : a } -> { b | minutes : a }
s_minutes value__ record__ =
    { record__ | minutes = value__ }


s_missing : a -> { b | missing : a } -> { b | missing : a }
s_missing value__ record__ =
    { record__ | missing = value__ }


s_modal : a -> { b | modal : a } -> { b | modal : a }
s_modal value__ record__ =
    { record__ | modal = value__ }


s_model : a -> { b | model : a } -> { b | model : a }
s_model value__ record__ =
    { record__ | model = value__ }


s_month : a -> { b | month : a } -> { b | month : a }
s_month value__ record__ =
    { record__ | month = value__ }


s_months : a -> { b | months : a } -> { b | months : a }
s_months value__ record__ =
    { record__ | months = value__ }


s_msg : a -> { b | msg : a } -> { b | msg : a }
s_msg value__ record__ =
    { record__ | msg = value__ }


s_multiline : a -> { b | multiline : a } -> { b | multiline : a }
s_multiline value__ record__ =
    { record__ | multiline = value__ }


s_name : a -> { b | name : a } -> { b | name : a }
s_name value__ record__ =
    { record__ | name = value__ }


s_namespace : a -> { b | namespace : a } -> { b | namespace : a }
s_namespace value__ record__ =
    { record__ | namespace = value__ }


s_namespaces : a -> { b | namespaces : a } -> { b | namespaces : a }
s_namespaces value__ record__ =
    { record__ | namespaces = value__ }


s_navbar : a -> { b | navbar : a } -> { b | navbar : a }
s_navbar value__ record__ =
    { record__ | navbar = value__ }


s_navbarLeft : a -> { b | navbarLeft : a } -> { b | navbarLeft : a }
s_navbarLeft value__ record__ =
    { record__ | navbarLeft = value__ }


s_navbarRight : a -> { b | navbarRight : a } -> { b | navbarRight : a }
s_navbarRight value__ record__ =
    { record__ | navbarRight = value__ }


s_navigation : a -> { b | navigation : a } -> { b | navigation : a }
s_navigation value__ record__ =
    { record__ | navigation = value__ }


s_neg : a -> { b | neg : a } -> { b | neg : a }
s_neg value__ record__ =
    { record__ | neg = value__ }


s_negP : a -> { b | negP : a } -> { b | negP : a }
s_negP value__ record__ =
    { record__ | negP = value__ }


s_negativePrefix : a -> { b | negativePrefix : a } -> { b | negativePrefix : a }
s_negativePrefix value__ record__ =
    { record__ | negativePrefix = value__ }


s_negativeSuffix : a -> { b | negativeSuffix : a } -> { b | negativeSuffix : a }
s_negativeSuffix value__ record__ =
    { record__ | negativeSuffix = value__ }


s_neighbors : a -> { b | neighbors : a } -> { b | neighbors : a }
s_neighbors value__ record__ =
    { record__ | neighbors = value__ }


s_new : a -> { b | new : a } -> { b | new : a }
s_new value__ record__ =
    { record__ | new = value__ }


s_newLines : a -> { b | newLines : a } -> { b | newLines : a }
s_newLines value__ record__ =
    { record__ | newLines = value__ }


s_nextPage : a -> { b | nextPage : a } -> { b | nextPage : a }
s_nextPage value__ record__ =
    { record__ | nextPage = value__ }


s_noAddressRelations : a -> { b | noAddressRelations : a } -> { b | noAddressRelations : a }
s_noAddressRelations value__ record__ =
    { record__ | noAddressRelations = value__ }


s_noAddresses : a -> { b | noAddresses : a } -> { b | noAddresses : a }
s_noAddresses value__ record__ =
    { record__ | noAddresses = value__ }


s_noBlocks : a -> { b | noBlocks : a } -> { b | noBlocks : a }
s_noBlocks value__ record__ =
    { record__ | noBlocks = value__ }


s_noEntities : a -> { b | noEntities : a } -> { b | noEntities : a }
s_noEntities value__ record__ =
    { record__ | noEntities = value__ }


s_noIncomingTxs : a -> { b | noIncomingTxs : a } -> { b | noIncomingTxs : a }
s_noIncomingTxs value__ record__ =
    { record__ | noIncomingTxs = value__ }


s_noLabels : a -> { b | noLabels : a } -> { b | noLabels : a }
s_noLabels value__ record__ =
    { record__ | noLabels = value__ }


s_noOutgoingTxs : a -> { b | noOutgoingTxs : a } -> { b | noOutgoingTxs : a }
s_noOutgoingTxs value__ record__ =
    { record__ | noOutgoingTxs = value__ }


s_noTaggedAddresses : a -> { b | noTaggedAddresses : a } -> { b | noTaggedAddresses : a }
s_noTaggedAddresses value__ record__ =
    { record__ | noTaggedAddresses = value__ }


s_noTxs : a -> { b | noTxs : a } -> { b | noTxs : a }
s_noTxs value__ record__ =
    { record__ | noTxs = value__ }


s_node : a -> { b | node : a } -> { b | node : a }
s_node value__ record__ =
    { record__ | node = value__ }


s_nodeList : a -> { b | nodeList : a } -> { b | nodeList : a }
s_nodeList value__ record__ =
    { record__ | nodeList = value__ }


s_nodeListSize : a -> { b | nodeListSize : a } -> { b | nodeListSize : a }
s_nodeListSize value__ record__ =
    { record__ | nodeListSize = value__ }


s_nodeSeparatorToExpandHandle : a -> { b | nodeSeparatorToExpandHandle : a } -> { b | nodeSeparatorToExpandHandle : a }
s_nodeSeparatorToExpandHandle value__ record__ =
    { record__ | nodeSeparatorToExpandHandle = value__ }


s_nodeType : a -> { b | nodeType : a } -> { b | nodeType : a }
s_nodeType value__ record__ =
    { record__ | nodeType = value__ }


s_nodeTypeCustom : a -> { b | nodeTypeCustom : a } -> { b | nodeTypeCustom : a }
s_nodeTypeCustom value__ record__ =
    { record__ | nodeTypeCustom = value__ }


s_nodeTypeKeyedNode : a -> { b | nodeTypeKeyedNode : a } -> { b | nodeTypeKeyedNode : a }
s_nodeTypeKeyedNode value__ record__ =
    { record__ | nodeTypeKeyedNode = value__ }


s_nodeTypeNode : a -> { b | nodeTypeNode : a } -> { b | nodeTypeNode : a }
s_nodeTypeNode value__ record__ =
    { record__ | nodeTypeNode = value__ }


s_nodeTypeTagger : a -> { b | nodeTypeTagger : a } -> { b | nodeTypeTagger : a }
s_nodeTypeTagger value__ record__ =
    { record__ | nodeTypeTagger = value__ }


s_nodeTypeText : a -> { b | nodeTypeText : a } -> { b | nodeTypeText : a }
s_nodeTypeText value__ record__ =
    { record__ | nodeTypeText = value__ }


s_nodeTypeThunk : a -> { b | nodeTypeThunk : a } -> { b | nodeTypeThunk : a }
s_nodeTypeThunk value__ record__ =
    { record__ | nodeTypeThunk = value__ }


s_none : a -> { b | none : a } -> { b | none : a }
s_none value__ record__ =
    { record__ | none = value__ }


s_nowMs : a -> { b | nowMs : a } -> { b | nowMs : a }
s_nowMs value__ record__ =
    { record__ | nowMs = value__ }


s_numMessages : a -> { b | numMessages : a } -> { b | numMessages : a }
s_numMessages value__ record__ =
    { record__ | numMessages = value__ }


s_number : a -> { b | number : a } -> { b | number : a }
s_number value__ record__ =
    { record__ | number = value__ }


s_numberFormat : a -> { b | numberFormat : a } -> { b | numberFormat : a }
s_numberFormat value__ record__ =
    { record__ | numberFormat = value__ }


s_numberOrInfinite : a -> { b | numberOrInfinite : a } -> { b | numberOrInfinite : a }
s_numberOrInfinite value__ record__ =
    { record__ | numberOrInfinite = value__ }


s_numericValue : a -> { b | numericValue : a } -> { b | numericValue : a }
s_numericValue value__ record__ =
    { record__ | numericValue = value__ }


s_octal : a -> { b | octal : a } -> { b | octal : a }
s_octal value__ record__ =
    { record__ | octal = value__ }


s_offset : a -> { b | offset : a } -> { b | offset : a }
s_offset value__ record__ =
    { record__ | offset = value__ }


s_oldTime : a -> { b | oldTime : a } -> { b | oldTime : a }
s_oldTime value__ record__ =
    { record__ | oldTime = value__ }


s_onClick : a -> { b | onClick : a } -> { b | onClick : a }
s_onClick value__ record__ =
    { record__ | onClick = value__ }


s_onError : a -> { b | onError : a } -> { b | onError : a }
s_onError value__ record__ =
    { record__ | onError = value__ }


s_onFailure : a -> { b | onFailure : a } -> { b | onFailure : a }
s_onFailure value__ record__ =
    { record__ | onFailure = value__ }


s_onLoading : a -> { b | onLoading : a } -> { b | onLoading : a }
s_onLoading value__ record__ =
    { record__ | onLoading = value__ }


s_onNotAsked : a -> { b | onNotAsked : a } -> { b | onNotAsked : a }
s_onNotAsked value__ record__ =
    { record__ | onNotAsked = value__ }


s_onRequestComplete : a -> { b | onRequestComplete : a } -> { b | onRequestComplete : a }
s_onRequestComplete value__ record__ =
    { record__ | onRequestComplete = value__ }


s_onRouteChange : a -> { b | onRouteChange : a } -> { b | onRouteChange : a }
s_onRouteChange value__ record__ =
    { record__ | onRouteChange = value__ }


s_onSuccess : a -> { b | onSuccess : a } -> { b | onSuccess : a }
s_onSuccess value__ record__ =
    { record__ | onSuccess = value__ }


s_onUrlChange : a -> { b | onUrlChange : a } -> { b | onUrlChange : a }
s_onUrlChange value__ record__ =
    { record__ | onUrlChange = value__ }


s_onUrlRequest : a -> { b | onUrlRequest : a } -> { b | onUrlRequest : a }
s_onUrlRequest value__ record__ =
    { record__ | onUrlRequest = value__ }


s_only : a -> { b | only : a } -> { b | only : a }
s_only value__ record__ =
    { record__ | only = value__ }


s_open : a -> { b | open : a } -> { b | open : a }
s_open value__ record__ =
    { record__ | open = value__ }


s_optionalDecimal : a -> { b | optionalDecimal : a } -> { b | optionalDecimal : a }
s_optionalDecimal value__ record__ =
    { record__ | optionalDecimal = value__ }


s_options : a -> { b | options : a } -> { b | options : a }
s_options value__ record__ =
    { record__ | options = value__ }


s_ordinal : a -> { b | ordinal : a } -> { b | ordinal : a }
s_ordinal value__ record__ =
    { record__ | ordinal = value__ }


s_orientation : a -> { b | orientation : a } -> { b | orientation : a }
s_orientation value__ record__ =
    { record__ | orientation = value__ }


s_original : a -> { b | original : a } -> { b | original : a }
s_original value__ record__ =
    { record__ | original = value__ }


s_originalActual : a -> { b | originalActual : a } -> { b | originalActual : a }
s_originalActual value__ record__ =
    { record__ | originalActual = value__ }


s_originalExpected : a -> { b | originalExpected : a } -> { b | originalExpected : a }
s_originalExpected value__ record__ =
    { record__ | originalExpected = value__ }


s_otherwise : a -> { b | otherwise : a } -> { b | otherwise : a }
s_otherwise value__ record__ =
    { record__ | otherwise = value__ }


s_outDegree : a -> { b | outDegree : a } -> { b | outDegree : a }
s_outDegree value__ record__ =
    { record__ | outDegree = value__ }


s_outgoingPortValues : a -> { b | outgoingPortValues : a } -> { b | outgoingPortValues : a }
s_outgoingPortValues value__ record__ =
    { record__ | outgoingPortValues = value__ }


s_outline : a -> { b | outline : a } -> { b | outline : a }
s_outline value__ record__ =
    { record__ | outline = value__ }


s_outputValue : a -> { b | outputValue : a } -> { b | outputValue : a }
s_outputValue value__ record__ =
    { record__ | outputValue = value__ }


s_outputs : a -> { b | outputs : a } -> { b | outputs : a }
s_outputs value__ record__ =
    { record__ | outputs = value__ }


s_over : a -> { b | over : a } -> { b | over : a }
s_over value__ record__ =
    { record__ | over = value__ }


s_overflow : a -> { b | overflow : a } -> { b | overflow : a }
s_overflow value__ record__ =
    { record__ | overflow = value__ }


s_overflowWrap : a -> { b | overflowWrap : a } -> { b | overflowWrap : a }
s_overflowWrap value__ record__ =
    { record__ | overflowWrap = value__ }


s_overlay : a -> { b | overlay : a } -> { b | overlay : a }
s_overlay value__ record__ =
    { record__ | overlay = value__ }


s_page : a -> { b | page : a } -> { b | page : a }
s_page value__ record__ =
    { record__ | page = value__ }


s_params : a -> { b | params : a } -> { b | params : a }
s_params value__ record__ =
    { record__ | params = value__ }


s_parens : a -> { b | parens : a } -> { b | parens : a }
s_parens value__ record__ =
    { record__ | parens = value__ }


s_part : a -> { b | part : a } -> { b | part : a }
s_part value__ record__ =
    { record__ | part = value__ }


s_path : a -> { b | path : a } -> { b | path : a }
s_path value__ record__ =
    { record__ | path = value__ }


s_pathParams : a -> { b | pathParams : a } -> { b | pathParams : a }
s_pathParams value__ record__ =
    { record__ | pathParams = value__ }


s_paths : a -> { b | paths : a } -> { b | paths : a }
s_paths value__ record__ =
    { record__ | paths = value__ }


s_pids : a -> { b | pids : a } -> { b | pids : a }
s_pids value__ record__ =
    { record__ | pids = value__ }


s_plus : a -> { b | plus : a } -> { b | plus : a }
s_plus value__ record__ =
    { record__ | plus = value__ }


s_pointerDevice : a -> { b | pointerDevice : a } -> { b | pointerDevice : a }
s_pointerDevice value__ record__ =
    { record__ | pointerDevice = value__ }


s_pointerEvents : a -> { b | pointerEvents : a } -> { b | pointerEvents : a }
s_pointerEvents value__ record__ =
    { record__ | pointerEvents = value__ }


s_popout : a -> { b | popout : a } -> { b | popout : a }
s_popout value__ record__ =
    { record__ | popout = value__ }


s_port_ : a -> { b | port_ : a } -> { b | port_ : a }
s_port_ value__ record__ =
    { record__ | port_ = value__ }


s_position : a -> { b | position : a } -> { b | position : a }
s_position value__ record__ =
    { record__ | position = value__ }


s_positivePrefix : a -> { b | positivePrefix : a } -> { b | positivePrefix : a }
s_positivePrefix value__ record__ =
    { record__ | positivePrefix = value__ }


s_positiveSuffix : a -> { b | positiveSuffix : a } -> { b | positiveSuffix : a }
s_positiveSuffix value__ record__ =
    { record__ | positiveSuffix = value__ }


s_postdocComments : a -> { b | postdocComments : a } -> { b | postdocComments : a }
s_postdocComments value__ record__ =
    { record__ | postdocComments = value__ }


s_preambleComments : a -> { b | preambleComments : a } -> { b | preambleComments : a }
s_preambleComments value__ record__ =
    { record__ | preambleComments = value__ }


s_precision : a -> { b | precision : a } -> { b | precision : a }
s_precision value__ record__ =
    { record__ | precision = value__ }


s_predocComments : a -> { b | predocComments : a } -> { b | predocComments : a }
s_predocComments value__ record__ =
    { record__ | predocComments = value__ }


s_prefix : a -> { b | prefix : a } -> { b | prefix : a }
s_prefix value__ record__ =
    { record__ | prefix = value__ }


s_prefixBits : a -> { b | prefixBits : a } -> { b | prefixBits : a }
s_prefixBits value__ record__ =
    { record__ | prefixBits = value__ }


s_preventDefault : a -> { b | preventDefault : a } -> { b | preventDefault : a }
s_preventDefault value__ record__ =
    { record__ | preventDefault = value__ }


s_primary : a -> { b | primary : a } -> { b | primary : a }
s_primary value__ record__ =
    { record__ | primary = value__ }


s_priority : a -> { b | priority : a } -> { b | priority : a }
s_priority value__ record__ =
    { record__ | priority = value__ }


s_problem : a -> { b | problem : a } -> { b | problem : a }
s_problem value__ record__ =
    { record__ | problem = value__ }


s_problems : a -> { b | problems : a } -> { b | problems : a }
s_problems value__ record__ =
    { record__ | problems = value__ }


s_processes : a -> { b | processes : a } -> { b | processes : a }
s_processes value__ record__ =
    { record__ | processes = value__ }


s_program : a -> { b | program : a } -> { b | program : a }
s_program value__ record__ =
    { record__ | program = value__ }


s_protocol : a -> { b | protocol : a } -> { b | protocol : a }
s_protocol value__ record__ =
    { record__ | protocol = value__ }


s_query : a -> { b | query : a } -> { b | query : a }
s_query value__ record__ =
    { record__ | query = value__ }


s_queryParams : a -> { b | queryParams : a } -> { b | queryParams : a }
s_queryParams value__ record__ =
    { record__ | queryParams = value__ }


s_rates : a -> { b | rates : a } -> { b | rates : a }
s_rates value__ record__ =
    { record__ | rates = value__ }


s_ratio : a -> { b | ratio : a } -> { b | ratio : a }
s_ratio value__ record__ =
    { record__ | ratio = value__ }


s_reason : a -> { b | reason : a } -> { b | reason : a }
s_reason value__ record__ =
    { record__ | reason = value__ }


s_received : a -> { b | received : a } -> { b | received : a }
s_received value__ record__ =
    { record__ | received = value__ }


s_recent : a -> { b | recent : a } -> { b | recent : a }
s_recent value__ record__ =
    { record__ | recent = value__ }


s_red : a -> { b | red : a } -> { b | red : a }
s_red value__ record__ =
    { record__ | red = value__ }


s_refs : a -> { b | refs : a } -> { b | refs : a }
s_refs value__ record__ =
    { record__ | refs = value__ }


s_relation : a -> { b | relation : a } -> { b | relation : a }
s_relation value__ record__ =
    { record__ | relation = value__ }


s_remaining : a -> { b | remaining : a } -> { b | remaining : a }
s_remaining value__ record__ =
    { record__ | remaining = value__ }


s_removed : a -> { b | removed : a } -> { b | removed : a }
s_removed value__ record__ =
    { record__ | removed = value__ }


s_reqs : a -> { b | reqs : a } -> { b | reqs : a }
s_reqs value__ record__ =
    { record__ | reqs = value__ }


s_request : a -> { b | request : a } -> { b | request : a }
s_request value__ record__ =
    { record__ | request = value__ }


s_requestLimit : a -> { b | requestLimit : a } -> { b | requestLimit : a }
s_requestLimit value__ record__ =
    { record__ | requestLimit = value__ }


s_requestLimitRoot : a -> { b | requestLimitRoot : a } -> { b | requestLimitRoot : a }
s_requestLimitRoot value__ record__ =
    { record__ | requestLimitRoot = value__ }


s_requestReset : a -> { b | requestReset : a } -> { b | requestReset : a }
s_requestReset value__ record__ =
    { record__ | requestReset = value__ }


s_requestTimestamp : a -> { b | requestTimestamp : a } -> { b | requestTimestamp : a }
s_requestTimestamp value__ record__ =
    { record__ | requestTimestamp = value__ }


s_reserved : a -> { b | reserved : a } -> { b | reserved : a }
s_reserved value__ record__ =
    { record__ | reserved = value__ }


s_reset : a -> { b | reset : a } -> { b | reset : a }
s_reset value__ record__ =
    { record__ | reset = value__ }


s_resize : a -> { b | resize : a } -> { b | resize : a }
s_resize value__ record__ =
    { record__ | resize = value__ }


s_resolution : a -> { b | resolution : a } -> { b | resolution : a }
s_resolution value__ record__ =
    { record__ | resolution = value__ }


s_resolver : a -> { b | resolver : a } -> { b | resolver : a }
s_resolver value__ record__ =
    { record__ | resolver = value__ }


s_result : a -> { b | result : a } -> { b | result : a }
s_result value__ record__ =
    { record__ | result = value__ }


s_resultGroup : a -> { b | resultGroup : a } -> { b | resultGroup : a }
s_resultGroup value__ record__ =
    { record__ | resultGroup = value__ }


s_resultGroupList : a -> { b | resultGroupList : a } -> { b | resultGroupList : a }
s_resultGroupList value__ record__ =
    { record__ | resultGroupList = value__ }


s_resultGroupTitle : a -> { b | resultGroupTitle : a } -> { b | resultGroupTitle : a }
s_resultGroupTitle value__ record__ =
    { record__ | resultGroupTitle = value__ }


s_resultLine : a -> { b | resultLine : a } -> { b | resultLine : a }
s_resultLine value__ record__ =
    { record__ | resultLine = value__ }


s_resultLineIcon : a -> { b | resultLineIcon : a } -> { b | resultLineIcon : a }
s_resultLineIcon value__ record__ =
    { record__ | resultLineIcon = value__ }


s_resume : a -> { b | resume : a } -> { b | resume : a }
s_resume value__ record__ =
    { record__ | resume = value__ }


s_reverseGet : a -> { b | reverseGet : a } -> { b | reverseGet : a }
s_reverseGet value__ record__ =
    { record__ | reverseGet = value__ }


s_right : a -> { b | right : a } -> { b | right : a }
s_right value__ record__ =
    { record__ | right = value__ }


s_rightNow : a -> { b | rightNow : a } -> { b | rightNow : a }
s_rightNow value__ record__ =
    { record__ | rightNow = value__ }


s_root : a -> { b | root : a } -> { b | root : a }
s_root value__ record__ =
    { record__ | root = value__ }


s_rootAddress : a -> { b | rootAddress : a } -> { b | rootAddress : a }
s_rootAddress value__ record__ =
    { record__ | rootAddress = value__ }


s_row : a -> { b | row : a } -> { b | row : a }
s_row value__ record__ =
    { record__ | row = value__ }


s_run : a -> { b | run : a } -> { b | run : a }
s_run value__ record__ =
    { record__ | run = value__ }


s_runs : a -> { b | runs : a } -> { b | runs : a }
s_runs value__ record__ =
    { record__ | runs = value__ }


s_sanitize : a -> { b | sanitize : a } -> { b | sanitize : a }
s_sanitize value__ record__ =
    { record__ | sanitize = value__ }


s_saturation : a -> { b | saturation : a } -> { b | saturation : a }
s_saturation value__ record__ =
    { record__ | saturation = value__ }


s_saturationFactor : a -> { b | saturationFactor : a } -> { b | saturationFactor : a }
s_saturationFactor value__ record__ =
    { record__ | saturationFactor = value__ }


s_scaled : a -> { b | scaled : a } -> { b | scaled : a }
s_scaled value__ record__ =
    { record__ | scaled = value__ }


s_scanningProcess : a -> { b | scanningProcess : a } -> { b | scanningProcess : a }
s_scanningProcess value__ record__ =
    { record__ | scanningProcess = value__ }


s_scene : a -> { b | scene : a } -> { b | scene : a }
s_scene value__ record__ =
    { record__ | scene = value__ }


s_scriptingSupport : a -> { b | scriptingSupport : a } -> { b | scriptingSupport : a }
s_scriptingSupport value__ record__ =
    { record__ | scriptingSupport = value__ }


s_scroll : a -> { b | scroll : a } -> { b | scroll : a }
s_scroll value__ record__ =
    { record__ | scroll = value__ }


s_search : a -> { b | search : a } -> { b | search : a }
s_search value__ record__ =
    { record__ | search = value__ }


s_seconds : a -> { b | seconds : a } -> { b | seconds : a }
s_seconds value__ record__ =
    { record__ | seconds = value__ }


s_sectionBelowHeader : a -> { b | sectionBelowHeader : a } -> { b | sectionBelowHeader : a }
s_sectionBelowHeader value__ record__ =
    { record__ | sectionBelowHeader = value__ }


s_seed : a -> { b | seed : a } -> { b | seed : a }
s_seed value__ record__ =
    { record__ | seed = value__ }


s_sent : a -> { b | sent : a } -> { b | sent : a }
s_sent value__ record__ =
    { record__ | sent = value__ }


s_separator : a -> { b | separator : a } -> { b | separator : a }
s_separator value__ record__ =
    { record__ | separator = value__ }


s_shift : a -> { b | shift : a } -> { b | shift : a }
s_shift value__ record__ =
    { record__ | shift = value__ }


s_signed : a -> { b | signed : a } -> { b | signed : a }
s_signed value__ record__ =
    { record__ | signed = value__ }


s_size : a -> { b | size : a } -> { b | size : a }
s_size value__ record__ =
    { record__ | size = value__ }


s_skipped : a -> { b | skipped : a } -> { b | skipped : a }
s_skipped value__ record__ =
    { record__ | skipped = value__ }


s_smaller : a -> { b | smaller : a } -> { b | smaller : a }
s_smaller value__ record__ =
    { record__ | smaller = value__ }


s_smartypants : a -> { b | smartypants : a } -> { b | smartypants : a }
s_smartypants value__ record__ =
    { record__ | smartypants = value__ }


s_snapshots : a -> { b | snapshots : a } -> { b | snapshots : a }
s_snapshots value__ record__ =
    { record__ | snapshots = value__ }


s_snippets : a -> { b | snippets : a } -> { b | snippets : a }
s_snippets value__ record__ =
    { record__ | snippets = value__ }


s_someDaysAgo : a -> { b | someDaysAgo : a } -> { b | someDaysAgo : a }
s_someDaysAgo value__ record__ =
    { record__ | someDaysAgo = value__ }


s_someHoursAgo : a -> { b | someHoursAgo : a } -> { b | someHoursAgo : a }
s_someHoursAgo value__ record__ =
    { record__ | someHoursAgo = value__ }


s_someMinutesAgo : a -> { b | someMinutesAgo : a } -> { b | someMinutesAgo : a }
s_someMinutesAgo value__ record__ =
    { record__ | someMinutesAgo = value__ }


s_someMonthsAgo : a -> { b | someMonthsAgo : a } -> { b | someMonthsAgo : a }
s_someMonthsAgo value__ record__ =
    { record__ | someMonthsAgo = value__ }


s_someSecondsAgo : a -> { b | someSecondsAgo : a } -> { b | someSecondsAgo : a }
s_someSecondsAgo value__ record__ =
    { record__ | someSecondsAgo = value__ }


s_someYearsAgo : a -> { b | someYearsAgo : a } -> { b | someYearsAgo : a }
s_someYearsAgo value__ record__ =
    { record__ | someYearsAgo = value__ }


s_source : a -> { b | source : a } -> { b | source : a }
s_source value__ record__ =
    { record__ | source = value__ }


s_spaces : a -> { b | spaces : a } -> { b | spaces : a }
s_spaces value__ record__ =
    { record__ | spaces = value__ }


s_src : a -> { b | src : a } -> { b | src : a }
s_src value__ record__ =
    { record__ | src = value__ }


s_start : a -> { b | start : a } -> { b | start : a }
s_start value__ record__ =
    { record__ | start = value__ }


s_state : a -> { b | state : a } -> { b | state : a }
s_state value__ record__ =
    { record__ | state = value__ }


s_stats : a -> { b | stats : a } -> { b | stats : a }
s_stats value__ record__ =
    { record__ | stats = value__ }


s_statusCode : a -> { b | statusCode : a } -> { b | statusCode : a }
s_statusCode value__ record__ =
    { record__ | statusCode = value__ }


s_statusText : a -> { b | statusText : a } -> { b | statusText : a }
s_statusText value__ record__ =
    { record__ | statusText = value__ }


s_stopPropagation : a -> { b | stopPropagation : a } -> { b | stopPropagation : a }
s_stopPropagation value__ record__ =
    { record__ | stopPropagation = value__ }


s_store : a -> { b | store : a } -> { b | store : a }
s_store value__ record__ =
    { record__ | store = value__ }


s_strValue : a -> { b | strValue : a } -> { b | strValue : a }
s_strValue value__ record__ =
    { record__ | strValue = value__ }


s_stringAttributes : a -> { b | stringAttributes : a } -> { b | stringAttributes : a }
s_stringAttributes value__ record__ =
    { record__ | stringAttributes = value__ }


s_styles : a -> { b | styles : a } -> { b | styles : a }
s_styles value__ record__ =
    { record__ | styles = value__ }


s_submatches : a -> { b | submatches : a } -> { b | submatches : a }
s_submatches value__ record__ =
    { record__ | submatches = value__ }


s_subs : a -> { b | subs : a } -> { b | subs : a }
s_subs value__ record__ =
    { record__ | subs = value__ }


s_subscription : a -> { b | subscription : a } -> { b | subscription : a }
s_subscription value__ record__ =
    { record__ | subscription = value__ }


s_subscriptions : a -> { b | subscriptions : a } -> { b | subscriptions : a }
s_subscriptions value__ record__ =
    { record__ | subscriptions = value__ }


s_suffix : a -> { b | suffix : a } -> { b | suffix : a }
s_suffix value__ record__ =
    { record__ | suffix = value__ }


s_svgRoot : a -> { b | svgRoot : a } -> { b | svgRoot : a }
s_svgRoot value__ record__ =
    { record__ | svgRoot = value__ }


s_symbol : a -> { b | symbol : a } -> { b | symbol : a }
s_symbol value__ record__ =
    { record__ | symbol = value__ }


s_system : a -> { b | system : a } -> { b | system : a }
s_system value__ record__ =
    { record__ | system = value__ }


s_table : a -> { b | table : a } -> { b | table : a }
s_table value__ record__ =
    { record__ | table = value__ }


s_tableCellKey : a -> { b | tableCellKey : a } -> { b | tableCellKey : a }
s_tableCellKey value__ record__ =
    { record__ | tableCellKey = value__ }


s_tableCellValue : a -> { b | tableCellValue : a } -> { b | tableCellValue : a }
s_tableCellValue value__ record__ =
    { record__ | tableCellValue = value__ }


s_tableLayout : a -> { b | tableLayout : a } -> { b | tableLayout : a }
s_tableLayout value__ record__ =
    { record__ | tableLayout = value__ }


s_tableRow : a -> { b | tableRow : a } -> { b | tableRow : a }
s_tableRow value__ record__ =
    { record__ | tableRow = value__ }


s_tableWrapper : a -> { b | tableWrapper : a } -> { b | tableWrapper : a }
s_tableWrapper value__ record__ =
    { record__ | tableWrapper = value__ }


s_tableWrapperInner : a -> { b | tableWrapperInner : a } -> { b | tableWrapperInner : a }
s_tableWrapperInner value__ record__ =
    { record__ | tableWrapperInner = value__ }


s_tables : a -> { b | tables : a } -> { b | tables : a }
s_tables value__ record__ =
    { record__ | tables = value__ }


s_tag : a -> { b | tag : a } -> { b | tag : a }
s_tag value__ record__ =
    { record__ | tag = value__ }


s_tagger : a -> { b | tagger : a } -> { b | tagger : a }
s_tagger value__ record__ =
    { record__ | tagger = value__ }


s_taggers : a -> { b | taggers : a } -> { b | taggers : a }
s_taggers value__ record__ =
    { record__ | taggers = value__ }


s_tagpackUri : a -> { b | tagpackUri : a } -> { b | tagpackUri : a }
s_tagpackUri value__ record__ =
    { record__ | tagpackUri = value__ }


s_tags : a -> { b | tags : a } -> { b | tags : a }
s_tags value__ record__ =
    { record__ | tags = value__ }


s_tail : a -> { b | tail : a } -> { b | tail : a }
s_tail value__ record__ =
    { record__ | tail = value__ }


s_taxonomy : a -> { b | taxonomy : a } -> { b | taxonomy : a }
s_taxonomy value__ record__ =
    { record__ | taxonomy = value__ }


s_text : a -> { b | text : a } -> { b | text : a }
s_text value__ record__ =
    { record__ | text = value__ }


s_textDecorationLine : a -> { b | textDecorationLine : a } -> { b | textDecorationLine : a }
s_textDecorationLine value__ record__ =
    { record__ | textDecorationLine = value__ }


s_textDecorationStyle : a -> { b | textDecorationStyle : a } -> { b | textDecorationStyle : a }
s_textDecorationStyle value__ record__ =
    { record__ | textDecorationStyle = value__ }


s_textIndent : a -> { b | textIndent : a } -> { b | textIndent : a }
s_textIndent value__ record__ =
    { record__ | textIndent = value__ }


s_textOrientation : a -> { b | textOrientation : a } -> { b | textOrientation : a }
s_textOrientation value__ record__ =
    { record__ | textOrientation = value__ }


s_textOverflow : a -> { b | textOverflow : a } -> { b | textOverflow : a }
s_textOverflow value__ record__ =
    { record__ | textOverflow = value__ }


s_textRendering : a -> { b | textRendering : a } -> { b | textRendering : a }
s_textRendering value__ record__ =
    { record__ | textRendering = value__ }


s_textTransform : a -> { b | textTransform : a } -> { b | textTransform : a }
s_textTransform value__ record__ =
    { record__ | textTransform = value__ }


s_textarea : a -> { b | textarea : a } -> { b | textarea : a }
s_textarea value__ record__ =
    { record__ | textarea = value__ }


s_theme : a -> { b | theme : a } -> { b | theme : a }
s_theme value__ record__ =
    { record__ | theme = value__ }


s_thousand : a -> { b | thousand : a } -> { b | thousand : a }
s_thousand value__ record__ =
    { record__ | thousand = value__ }


s_thousandSeparator : a -> { b | thousandSeparator : a } -> { b | thousandSeparator : a }
s_thousandSeparator value__ record__ =
    { record__ | thousandSeparator = value__ }


s_thousands : a -> { b | thousands : a } -> { b | thousands : a }
s_thousands value__ record__ =
    { record__ | thousands = value__ }


s_tickLength : a -> { b | tickLength : a } -> { b | tickLength : a }
s_tickLength value__ record__ =
    { record__ | tickLength = value__ }


s_timeLang : a -> { b | timeLang : a } -> { b | timeLang : a }
s_timeLang value__ record__ =
    { record__ | timeLang = value__ }


s_timeout : a -> { b | timeout : a } -> { b | timeout : a }
s_timeout value__ record__ =
    { record__ | timeout = value__ }


s_timestamp : a -> { b | timestamp : a } -> { b | timestamp : a }
s_timestamp value__ record__ =
    { record__ | timestamp = value__ }


s_timing : a -> { b | timing : a } -> { b | timing : a }
s_timing value__ record__ =
    { record__ | timing = value__ }


s_tipe : a -> { b | tipe : a } -> { b | tipe : a }
s_tipe value__ record__ =
    { record__ | tipe = value__ }


s_title : a -> { b | title : a } -> { b | title : a }
s_title value__ record__ =
    { record__ | title = value__ }


s_toAddress : a -> { b | toAddress : a } -> { b | toAddress : a }
s_toAddress value__ record__ =
    { record__ | toAddress = value__ }


s_toAmPm : a -> { b | toAmPm : a } -> { b | toAmPm : a }
s_toAmPm value__ record__ =
    { record__ | toAmPm = value__ }


s_toMonthAbbreviation : a -> { b | toMonthAbbreviation : a } -> { b | toMonthAbbreviation : a }
s_toMonthAbbreviation value__ record__ =
    { record__ | toMonthAbbreviation = value__ }


s_toMonthName : a -> { b | toMonthName : a } -> { b | toMonthName : a }
s_toMonthName value__ record__ =
    { record__ | toMonthName = value__ }


s_toMsg : a -> { b | toMsg : a } -> { b | toMsg : a }
s_toMsg value__ record__ =
    { record__ | toMsg = value__ }


s_toOrdinalSuffix : a -> { b | toOrdinalSuffix : a } -> { b | toOrdinalSuffix : a }
s_toOrdinalSuffix value__ record__ =
    { record__ | toOrdinalSuffix = value__ }


s_toWeekdayAbbreviation : a -> { b | toWeekdayAbbreviation : a } -> { b | toWeekdayAbbreviation : a }
s_toWeekdayAbbreviation value__ record__ =
    { record__ | toWeekdayAbbreviation = value__ }


s_toWeekdayName : a -> { b | toWeekdayName : a } -> { b | toWeekdayName : a }
s_toWeekdayName value__ record__ =
    { record__ | toWeekdayName = value__ }


s_tool : a -> { b | tool : a } -> { b | tool : a }
s_tool value__ record__ =
    { record__ | tool = value__ }


s_totalInput : a -> { b | totalInput : a } -> { b | totalInput : a }
s_totalInput value__ record__ =
    { record__ | totalInput = value__ }


s_totalOutput : a -> { b | totalOutput : a } -> { b | totalOutput : a }
s_totalOutput value__ record__ =
    { record__ | totalOutput = value__ }


s_totalReceived : a -> { b | totalReceived : a } -> { b | totalReceived : a }
s_totalReceived value__ record__ =
    { record__ | totalReceived = value__ }


s_totalSpent : a -> { b | totalSpent : a } -> { b | totalSpent : a }
s_totalSpent value__ record__ =
    { record__ | totalSpent = value__ }


s_touchAction : a -> { b | touchAction : a } -> { b | touchAction : a }
s_touchAction value__ record__ =
    { record__ | touchAction = value__ }


s_tracker : a -> { b | tracker : a } -> { b | tracker : a }
s_tracker value__ record__ =
    { record__ | tracker = value__ }


s_trailing : a -> { b | trailing : a } -> { b | trailing : a }
s_trailing value__ record__ =
    { record__ | trailing = value__ }


s_transform : a -> { b | transform : a } -> { b | transform : a }
s_transform value__ record__ =
    { record__ | transform = value__ }


s_transformBox : a -> { b | transformBox : a } -> { b | transformBox : a }
s_transformBox value__ record__ =
    { record__ | transformBox = value__ }


s_transformStyle : a -> { b | transformStyle : a } -> { b | transformStyle : a }
s_transformStyle value__ record__ =
    { record__ | transformStyle = value__ }


s_trillion : a -> { b | trillion : a } -> { b | trillion : a }
s_trillion value__ record__ =
    { record__ | trillion = value__ }


s_txHash : a -> { b | txHash : a } -> { b | txHash : a }
s_txHash value__ record__ =
    { record__ | txHash = value__ }


s_txType : a -> { b | txType : a } -> { b | txType : a }
s_txType value__ record__ =
    { record__ | txType = value__ }


s_txs : a -> { b | txs : a } -> { b | txs : a }
s_txs value__ record__ =
    { record__ | txs = value__ }


s_types : a -> { b | types : a } -> { b | types : a }
s_types value__ record__ =
    { record__ | types = value__ }


s_unions : a -> { b | unions : a } -> { b | unions : a }
s_unions value__ record__ =
    { record__ | unions = value__ }


s_unitLabel : a -> { b | unitLabel : a } -> { b | unitLabel : a }
s_unitLabel value__ record__ =
    { record__ | unitLabel = value__ }


s_units : a -> { b | units : a } -> { b | units : a }
s_units value__ record__ =
    { record__ | units = value__ }


s_unvisited : a -> { b | unvisited : a } -> { b | unvisited : a }
s_unvisited value__ record__ =
    { record__ | unvisited = value__ }


s_update : a -> { b | update : a } -> { b | update : a }
s_update value__ record__ =
    { record__ | update = value__ }


s_updateFrequency : a -> { b | updateFrequency : a } -> { b | updateFrequency : a }
s_updateFrequency value__ record__ =
    { record__ | updateFrequency = value__ }


s_updatedEntity : a -> { b | updatedEntity : a } -> { b | updatedEntity : a }
s_updatedEntity value__ record__ =
    { record__ | updatedEntity = value__ }


s_uri : a -> { b | uri : a } -> { b | uri : a }
s_uri value__ record__ =
    { record__ | uri = value__ }


s_url : a -> { b | url : a } -> { b | url : a }
s_url value__ record__ =
    { record__ | url = value__ }


s_user : a -> { b | user : a } -> { b | user : a }
s_user value__ record__ =
    { record__ | user = value__ }


s_value : a -> { b | value : a } -> { b | value : a }
s_value value__ record__ =
    { record__ | value = value__ }


s_version : a -> { b | version : a } -> { b | version : a }
s_version value__ record__ =
    { record__ | version = value__ }


s_versions : a -> { b | versions : a } -> { b | versions : a }
s_versions value__ record__ =
    { record__ | versions = value__ }


s_view : a -> { b | view : a } -> { b | view : a }
s_view value__ record__ =
    { record__ | view = value__ }


s_viewport : a -> { b | viewport : a } -> { b | viewport : a }
s_viewport value__ record__ =
    { record__ | viewport = value__ }


s_virtualDom : a -> { b | virtualDom : a } -> { b | virtualDom : a }
s_virtualDom value__ record__ =
    { record__ | virtualDom = value__ }


s_visibility : a -> { b | visibility : a } -> { b | visibility : a }
s_visibility value__ record__ =
    { record__ | visibility = value__ }


s_visited : a -> { b | visited : a } -> { b | visited : a }
s_visited value__ record__ =
    { record__ | visited = value__ }


s_white : a -> { b | white : a } -> { b | white : a }
s_white value__ record__ =
    { record__ | white = value__ }


s_whiteSpace : a -> { b | whiteSpace : a } -> { b | whiteSpace : a }
s_whiteSpace value__ record__ =
    { record__ | whiteSpace = value__ }


s_width : a -> { b | width : a } -> { b | width : a }
s_width value__ record__ =
    { record__ | width = value__ }


s_withinFocus : a -> { b | withinFocus : a } -> { b | withinFocus : a }
s_withinFocus value__ record__ =
    { record__ | withinFocus = value__ }


s_without : a -> { b | without : a } -> { b | without : a }
s_without value__ record__ =
    { record__ | without = value__ }


s_word : a -> { b | word : a } -> { b | word : a }
s_word value__ record__ =
    { record__ | word = value__ }


s_workQueue : a -> { b | workQueue : a } -> { b | workQueue : a }
s_workQueue value__ record__ =
    { record__ | workQueue = value__ }


s_wrap : a -> { b | wrap : a } -> { b | wrap : a }
s_wrap value__ record__ =
    { record__ | wrap = value__ }


s_x : a -> { b | x : a } -> { b | x : a }
s_x value__ record__ =
    { record__ | x = value__ }


s_y : a -> { b | y : a } -> { b | y : a }
s_y value__ record__ =
    { record__ | y = value__ }


s_year : a -> { b | year : a } -> { b | year : a }
s_year value__ record__ =
    { record__ | year = value__ }


s_years : a -> { b | years : a } -> { b | years : a }
s_years value__ record__ =
    { record__ | years = value__ }


s_z : a -> { b | z : a } -> { b | z : a }
s_z value__ record__ =
    { record__ | z = value__ }


s_zeroPrefix : a -> { b | zeroPrefix : a } -> { b | zeroPrefix : a }
s_zeroPrefix value__ record__ =
    { record__ | zeroPrefix = value__ }


s_zeroSuffix : a -> { b | zeroSuffix : a } -> { b | zeroSuffix : a }
s_zeroSuffix value__ record__ =
    { record__ | zeroSuffix = value__ }


s_zone : a -> { b | zone : a } -> { b | zone : a }
s_zone value__ record__ =
    { record__ | zone = value__ }
